unit trsummary1formu;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ppBands, ppClass, ppCtrls, myChkBox, ppVar, ppPrnabl, ppCache,
  ppProd, ppReport, ppComm, ppRelatv, ppDB, ppDBPipe, ppDBBDE, DB, DBClient,
  ppViewr, ppStrtch, ppMemo, ppParameter;

type
  Tfrmtrsummary1 = class(TForm)
    Query1: TClientDataSet;
    Query2: TClientDataSet;
    Query3: TClientDataSet;
    DataSource1: TDataSource;
    ppBDEPipeline1: TppBDEPipeline;
    ppReport1: TppReport;
    ppHeaderBand1: TppHeaderBand;
    ppLabel1: TppLabel;
    title001: TppLabel;
    ppLabel2: TppLabel;
    ppDBText1: TppDBText;
    ppLabel3: TppLabel;
    ppDBText2: TppDBText;
    ppLabel4: TppLabel;
    ppDBText3: TppDBText;
    ppLabel5: TppLabel;
    ppDBText4: TppDBText;
    ppLabel6: TppLabel;
    ppSystemVariable1: TppSystemVariable;
    ppLabel7: TppLabel;
    ppSystemVariable2: TppSystemVariable;
    ppShape1: TppShape;
    ppLabel8: TppLabel;
    ppLabel12: TppLabel;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLabel17: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppLine5: TppLine;
    ppLine7: TppLine;
    ppLine9: TppLine;
    ppLine11: TppLine;
    ppLine13: TppLine;
    ppLabel20: TppLabel;
    ppLabel21: TppLabel;
    ppLine15: TppLine;
    ppLabel22: TppLabel;
    ppLabel23: TppLabel;
    ppLine17: TppLine;
    ppLine19: TppLine;
    ppLine20: TppLine;
    ppLine21: TppLine;
    ppLabel24: TppLabel;
    ppLabel25: TppLabel;
    ppLine25: TppLine;
    ppLabel26: TppLabel;
    ppLabel27: TppLabel;
    ppLabel28: TppLabel;
    ppLabel29: TppLabel;
    ppLabel30: TppLabel;
    ppLabel31: TppLabel;
    ppLabel32: TppLabel;
    ppLabel33: TppLabel;
    ppLabel34: TppLabel;
    ppLabel35: TppLabel;
    ppLabel36: TppLabel;
    ppLabel37: TppLabel;
    ppLabel38: TppLabel;
    ppLabel39: TppLabel;
    ppLine76: TppLine;
    ppLine77: TppLine;
    ppLine78: TppLine;
    ppLine79: TppLine;
    ppLine80: TppLine;
    ppLine81: TppLine;
    ppLine82: TppLine;
    ppLine83: TppLine;
    ppLine84: TppLine;
    ppLabel43: TppLabel;
    ttlwo: TppLabel;
    ppLabel11: TppLabel;
    ppLabel85: TppLabel;
    ppLabel88: TppLabel;
    ppLabel94: TppLabel;
    ppLabel103: TppLabel;
    ppLine90: TppLine;
    ppLabel104: TppLabel;
    ppLine126: TppLine;
    ppLabel124: TppLabel;
    ppLine128: TppLine;
    ppLabel126: TppLabel;
    ppLine130: TppLine;
    ppLabel127: TppLabel;
    ppLine132: TppLine;
    ppLabel128: TppLabel;
    ppLine134: TppLine;
    ppLabel129: TppLabel;
    ppLine136: TppLine;
    ppLine138: TppLine;
    ppLabel130: TppLabel;
    ppLabel131: TppLabel;
    ppLine140: TppLine;
    ppLabel132: TppLabel;
    ppLine142: TppLine;
    ppLabel133: TppLabel;
    ppLine144: TppLine;
    ppLine145: TppLine;
    ppLabel134: TppLabel;
    ppLabel135: TppLabel;
    ppDetailBand1: TppDetailBand;
    ppShape2: TppShape;
    ppDBText5: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppLine6: TppLine;
    ppLine8: TppLine;
    ppLine10: TppLine;
    ppLine12: TppLine;
    ppLine14: TppLine;
    ppLine16: TppLine;
    ppLine18: TppLine;
    ppLine22: TppLine;
    ppLine23: TppLine;
    ppLine24: TppLine;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppLine67: TppLine;
    ppLine68: TppLine;
    ppLine69: TppLine;
    ppLine70: TppLine;
    ppLine71: TppLine;
    ppLine72: TppLine;
    ppLine73: TppLine;
    ppLine74: TppLine;
    ppLine75: TppLine;
    ppLine111: TppLine;
    ppDBText47: TppDBText;
    ppLine127: TppLine;
    ppDBText48: TppDBText;
    ppLine129: TppLine;
    ppLine131: TppLine;
    ppDBText49: TppDBText;
    ppLine133: TppLine;
    ppDBText57: TppDBText;
    ppLine135: TppLine;
    ppDBText67: TppDBText;
    ppLine137: TppLine;
    ppLine139: TppLine;
    ppDBText68: TppDBText;
    ppLine141: TppLine;
    ppLine143: TppLine;
    ppLine146: TppLine;
    ppLine147: TppLine;
    cmp001: TmyCheckBox;
    cmp101: TmyCheckBox;
    cmps01: TmyCheckBox;
    cmp201: TmyCheckBox;
    cmp301: TmyCheckBox;
    cmp302: TmyCheckBox;
    cmp401: TmyCheckBox;
    cmpi01: TmyCheckBox;
    ppFooterBand1: TppFooterBand;
    ppSummaryBand1: TppSummaryBand;
    ppLabel41: TppLabel;
    ppDBCalc1: TppDBCalc;
    ppDBCalc2: TppDBCalc;
    ppDBCalc3: TppDBCalc;
    ppDBCalc4: TppDBCalc;
    ppDBCalc5: TppDBCalc;
    ppDBCalc6: TppDBCalc;
    ppDBCalc7: TppDBCalc;
    ppDBCalc8: TppDBCalc;
    ppDBCalc9: TppDBCalc;
    ppDBCalc28: TppDBCalc;
    ppDBCalc29: TppDBCalc;
    ppDBCalc30: TppDBCalc;
    ppDBCalc31: TppDBCalc;
    ppDBCalc32: TppDBCalc;
    ppDBCalc33: TppDBCalc;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppLine1: TppLine;
    ppLine2: TppLine;
    ppLine3: TppLine;
    ppLine4: TppLine;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppShape4: TppShape;
    ppMemo1: TppMemo;
    ppReport2: TppReport;
    ppHeaderBand3: TppHeaderBand;
    ppLabel53: TppLabel;
    title002: TppLabel;
    ppLabel86: TppLabel;
    ppDBText45: TppDBText;
    ppLabel87: TppLabel;
    ppDBText46: TppDBText;
    ppLabel90: TppLabel;
    ppDBText51: TppDBText;
    ppLabel91: TppLabel;
    ppSystemVariable5: TppSystemVariable;
    ppLabel92: TppLabel;
    ppSystemVariable6: TppSystemVariable;
    ppShape5: TppShape;
    ppLabel95: TppLabel;
    ppLabel96: TppLabel;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppLabel99: TppLabel;
    ppLabel100: TppLabel;
    ppLabel101: TppLabel;
    ppLabel102: TppLabel;
    ppLabel105: TppLabel;
    ppLabel106: TppLabel;
    ppLine86: TppLine;
    ppLine87: TppLine;
    ppLine88: TppLine;
    ppLine89: TppLine;
    ppLine91: TppLine;
    ppLine92: TppLine;
    ppLabel107: TppLabel;
    ppLabel108: TppLabel;
    ppLine93: TppLine;
    ppLabel109: TppLabel;
    ppLabel110: TppLabel;
    ppLine94: TppLine;
    ppLine95: TppLine;
    ppLine96: TppLine;
    ppLine97: TppLine;
    ppLabel111: TppLabel;
    ppLabel112: TppLabel;
    ppLine98: TppLine;
    ppLabel113: TppLabel;
    ppLabel114: TppLabel;
    ppLabel115: TppLabel;
    ppLabel116: TppLabel;
    ppLabel117: TppLabel;
    ppLabel118: TppLabel;
    ppLabel119: TppLabel;
    ppLabel120: TppLabel;
    ppLabel121: TppLabel;
    ppLabel122: TppLabel;
    ppLabel123: TppLabel;
    ppLabel125: TppLabel;
    ppLabel137: TppLabel;
    ppLabel140: TppLabel;
    ppLine99: TppLine;
    ppLine100: TppLine;
    ppLine101: TppLine;
    ppLine102: TppLine;
    ppLine103: TppLine;
    ppLine104: TppLine;
    ppLine105: TppLine;
    ppLine106: TppLine;
    ppLine107: TppLine;
    ppLabel158: TppLabel;
    ppLabel177: TppLabel;
    ppLabel181: TppLabel;
    ppLabel196: TppLabel;
    ppLabel197: TppLabel;
    ppLine108: TppLine;
    ppLabel198: TppLabel;
    ppLine109: TppLine;
    ppLabel199: TppLabel;
    ppLine110: TppLine;
    ppLabel200: TppLabel;
    ppLine112: TppLine;
    ppLabel201: TppLabel;
    ppLine113: TppLine;
    ppLabel202: TppLabel;
    ppLine114: TppLine;
    ppLabel203: TppLabel;
    ppLine115: TppLine;
    ppLine116: TppLine;
    ppLabel204: TppLabel;
    ppLabel205: TppLabel;
    ppLine117: TppLine;
    ppLabel206: TppLabel;
    ppLine118: TppLine;
    ppLabel207: TppLabel;
    ppLine119: TppLine;
    ppLine120: TppLine;
    ppLabel208: TppLabel;
    ppLabel209: TppLabel;
    ppLabel89: TppLabel;
    ppDBText50: TppDBText;
    ppDetailBand3: TppDetailBand;
    ppShape6: TppShape;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppDBText55: TppDBText;
    ppDBText56: TppDBText;
    ppDBText58: TppDBText;
    ppLine122: TppLine;
    ppLine123: TppLine;
    ppLine124: TppLine;
    ppLine125: TppLine;
    ppLine148: TppLine;
    ppLine155: TppLine;
    ppLine182: TppLine;
    ppLine189: TppLine;
    ppLine215: TppLine;
    ppLine216: TppLine;
    ppLine217: TppLine;
    ppDBText59: TppDBText;
    myDBCheckBox9: TmyDBCheckBox;
    myDBCheckBox10: TmyDBCheckBox;
    myDBCheckBox11: TmyDBCheckBox;
    myDBCheckBox12: TmyDBCheckBox;
    ppDBText60: TppDBText;
    ppDBText61: TppDBText;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppDBText64: TppDBText;
    ppDBText65: TppDBText;
    ppDBText66: TppDBText;
    ppDBText71: TppDBText;
    ppDBText72: TppDBText;
    ppDBText74: TppDBText;
    ppDBText82: TppDBText;
    ppLine218: TppLine;
    ppLine219: TppLine;
    ppLine220: TppLine;
    ppLine221: TppLine;
    ppLine222: TppLine;
    ppLine223: TppLine;
    ppLine224: TppLine;
    ppLine225: TppLine;
    ppLine226: TppLine;
    ppLine227: TppLine;
    ppDBText97: TppDBText;
    ppLine228: TppLine;
    ppDBText98: TppDBText;
    ppLine229: TppLine;
    ppLine230: TppLine;
    ppDBText99: TppDBText;
    ppLine231: TppLine;
    ppDBText100: TppDBText;
    ppLine232: TppLine;
    ppDBText101: TppDBText;
    ppLine233: TppLine;
    ppLine234: TppLine;
    ppDBText102: TppDBText;
    ppLine235: TppLine;
    myDBCheckBox25: TmyDBCheckBox;
    ppLine236: TppLine;
    myDBCheckBox26: TmyDBCheckBox;
    ppLine237: TppLine;
    ppLine238: TppLine;
    myDBCheckBox27: TmyDBCheckBox;
    myDBCheckBox28: TmyDBCheckBox;
    ppDBText103: TppDBText;
    ppDBText23: TppDBText;
    ppDBText24: TppDBText;
    ppFooterBand3: TppFooterBand;
    ppSummaryBand3: TppSummaryBand;
    ppLabel210: TppLabel;
    ppDBCalc19: TppDBCalc;
    ppDBCalc20: TppDBCalc;
    ppDBCalc21: TppDBCalc;
    ppDBCalc22: TppDBCalc;
    ppDBCalc23: TppDBCalc;
    ppDBCalc24: TppDBCalc;
    ppDBCalc25: TppDBCalc;
    ppDBCalc26: TppDBCalc;
    ppDBCalc27: TppDBCalc;
    ppDBCalc49: TppDBCalc;
    ppDBCalc50: TppDBCalc;
    ppDBCalc51: TppDBCalc;
    ppDBCalc52: TppDBCalc;
    ppDBCalc53: TppDBCalc;
    ppDBCalc54: TppDBCalc;
    ppDBCalc64: TppDBCalc;
    ppDBCalc66: TppDBCalc;
    ppShape3: TppShape;
    ppMemo2: TppMemo;
    ppGroup3: TppGroup;
    ppGroupHeaderBand3: TppGroupHeaderBand;
    ppGroupFooterBand3: TppGroupFooterBand;
    ppLabel44: TppLabel;
    ppDBCalc10: TppDBCalc;
    ppDBCalc11: TppDBCalc;
    ppDBCalc12: TppDBCalc;
    ppDBCalc13: TppDBCalc;
    ppDBCalc14: TppDBCalc;
    ppDBCalc15: TppDBCalc;
    ppDBCalc16: TppDBCalc;
    ppDBCalc17: TppDBCalc;
    ppDBCalc18: TppDBCalc;
    ppDBCalc55: TppDBCalc;
    ppDBCalc56: TppDBCalc;
    ppDBCalc57: TppDBCalc;
    ppDBCalc58: TppDBCalc;
    ppDBCalc59: TppDBCalc;
    ppDBCalc60: TppDBCalc;
    ppDBCalc63: TppDBCalc;
    ppDBCalc65: TppDBCalc;
    ppLine28: TppLine;
    ppLine29: TppLine;
    ppLabel45: TppLabel;
    ppDBText25: TppDBText;
    ppLabel46: TppLabel;
    ppDBText26: TppDBText;
    ppLabel47: TppLabel;
    ppLine30: TppLine;
    ppLine31: TppLine;
    ppLabel48: TppLabel;
    ppLabel49: TppLabel;
    ppDBText27: TppDBText;
    ppLabel50: TppLabel;
    ppLabel40: TppLabel;
    ppLabel42: TppLabel;
    myCheckBox2: TmyCheckBox;
    ppLabel51: TppLabel;
    ppLabel52: TppLabel;
    myCheckBox1: TmyCheckBox;
    ppLabel54: TppLabel;
    ppLabel55: TppLabel;
    myCheckBox3: TmyCheckBox;
    ppLabel56: TppLabel;
    ppLabel57: TppLabel;
    myCheckBox4: TmyCheckBox;
    procedure ppDetailBand1BeforePrint(Sender: TObject);
    procedure ppReport1PreviewFormCreate(Sender: TObject);
    procedure ppReport2PreviewFormCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmtrsummary1: Tfrmtrsummary1;

implementation

uses mainformu, worksheet, achievingformu, lwoformu;

{$R *.dfm}

procedure Tfrmtrsummary1.ppDetailBand1BeforePrint(Sender: TObject);
begin
  with query1 do begin
    close;
    params.clear;
    params.createparam(ftdatetime,'x1',ptinput);
    params.createparam(ftinteger,'x2',ptinput);
    commandtext:='select distinct cmp from tbl_tmp_transit where tm=:x1 and cmp=0 and did=:x2 and fccs='''+query3.fieldbyname('fccs').value+'''';
    params[0].asdatetime:=query3.fieldbyname('tm').value;
    params[1].asinteger:=query3.fieldbyname('did').value;
    open;
    if not fieldbyname('cmp').isnull then cmp001.Checked:=false else cmp001.Checked:=true;
  end;
  with query1 do begin
    close;
    params.clear;
    params.createparam(ftdatetime,'x1',ptinput);
    params.createparam(ftinteger,'x2',ptinput);
    commandtext:='select distinct cmp1 from tbl_tmp_transit where tm=:x1 and cmp1=0 and did=:x2 and fccs='''+query3.fieldbyname('fccs').value+'''';
    params[0].asdatetime:=query3.fieldbyname('tm').value;
    params[1].asinteger:=query3.fieldbyname('did').value;
    open;
    if not fieldbyname('cmp1').isnull then cmp101.Checked:=false else cmp101.Checked:=true;
  end;
  with query1 do begin
    close;
    params.clear;
    params.createparam(ftdatetime,'x1',ptinput);
    params.createparam(ftinteger,'x2',ptinput);
    commandtext:='select distinct cmps from tbl_tmp_transit where tm=:x1 and cmps=0 and did=:x2 and fccs='''+query3.fieldbyname('fccs').value+'''';
    params[0].asdatetime:=query3.fieldbyname('tm').value;
    params[1].asinteger:=query3.fieldbyname('did').value;
    open;
    if not fieldbyname('cmps').isnull then cmps01.Checked:=false else cmps01.Checked:=true;
  end;
  with query1 do begin
    close;
    params.clear;
    params.createparam(ftdatetime,'x1',ptinput);
    params.createparam(ftinteger,'x2',ptinput);
    commandtext:='select distinct cmp2 from tbl_tmp_transit where tm=:x1 and cmp2=0 and did=:x2 and fccs='''+query3.fieldbyname('fccs').value+'''';
    params[0].asdatetime:=query3.fieldbyname('tm').value;
    params[1].asinteger:=query3.fieldbyname('did').value;
    open;
    if not fieldbyname('cmp2').isnull then cmp201.Checked:=false else cmp201.Checked:=true;
  end;
  with query1 do begin
    close;
    params.clear;
    params.createparam(ftdatetime,'x1',ptinput);
    params.createparam(ftinteger,'x2',ptinput);
    commandtext:='select distinct cmp3 from tbl_tmp_transit where tm=:x1 and cmp3=0 and did=:x2 and fccs='''+query3.fieldbyname('fccs').value+'''';
    params[0].asdatetime:=query3.fieldbyname('tm').value;
    params[1].asinteger:=query3.fieldbyname('did').value;
    open;
    if not fieldbyname('cmp3').isnull then begin
      cmp301.Checked:=false;
      cmp302.Checked:=false;
    end else begin
      cmp301.Checked:=true;
      cmp302.Checked:=true;
    end;
  end;
  with query1 do begin
    close;
    params.clear;
    params.createparam(ftdatetime,'x1',ptinput);
    params.createparam(ftinteger,'x2',ptinput);
    commandtext:='select distinct cmp4 from tbl_tmp_transit where tm=:x1 and cmp4=0 and did=:x2 and fccs='''+query3.fieldbyname('fccs').value+'''';
    params[0].asdatetime:=query3.fieldbyname('tm').value;
    params[1].asinteger:=query3.fieldbyname('did').value;
    open;
    if not fieldbyname('cmp4').isnull then cmp401.Checked:=false else cmp401.Checked:=true;
  end;
  with query1 do begin
    close;
    params.clear;
    params.createparam(ftdatetime,'x1',ptinput);
    params.createparam(ftinteger,'x2',ptinput);
    commandtext:='select distinct cmpi from tbl_tmp_transit where tm=:x1 and cmpi=0 and did=:x2 and fccs='''+query3.fieldbyname('fccs').value+'''';
    params[0].asdatetime:=query3.fieldbyname('tm').value;
    params[1].asinteger:=query3.fieldbyname('did').value;
    open;
    if not fieldbyname('cmpi').isnull then cmpi01.Checked:=false else cmpi01.Checked:=true;
  end;
  {
  cmp001.Checked:=query3.fieldbyname('cmp').value;
  cmp101.Checked:=query3.fieldbyname('cmp1').value;
  cmps01.Checked:=query3.fieldbyname('cmps').value;
  cmp201.Checked:=query3.fieldbyname('cmp2').value;
  cmp301.Checked:=query3.fieldbyname('cmp3').value;
  cmp401.Checked:=query3.fieldbyname('cmp4').value;
  cmpi01.Checked:=query3.fieldbyname('cmpi').value;
  }
end;

procedure Tfrmtrsummary1.ppReport1PreviewFormCreate(Sender: TObject);
begin
  ppReport1.PreviewForm.WindowState:=wsMaximized;
  TppViewer(ppReport1.PreviewForm.Viewer).ZoomPercentage:=100;
end;

procedure Tfrmtrsummary1.ppReport2PreviewFormCreate(Sender: TObject);
begin
  ppReport2.PreviewForm.WindowState:=wsMaximized;
  TppViewer(ppReport2.PreviewForm.Viewer).ZoomPercentage:=100;
end;

end.
 