object frmdzxz: Tfrmdzxz
  Left = 372
  Top = 181
  Width = 233
  Height = 164
  BorderIcons = [biSystemMenu]
  Caption = '動作選擇'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object op1: TRadioButton
    Left = 47
    Top = 16
    Width = 134
    Height = 17
    Caption = '車縫作業計算表'
    Checked = True
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    TabStop = True
  end
  object op2: TRadioButton
    Left = 47
    Top = 56
    Width = 135
    Height = 17
    Caption = '周期機械計算表'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
  end
  object BitBtn1: TBitBtn
    Left = 40
    Top = 96
    Width = 57
    Height = 25
    Caption = '確定'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    OnClick = BitBtn1Click
  end
  object BitBtn2: TBitBtn
    Left = 128
    Top = 96
    Width = 57
    Height = 25
    Caption = '取消'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
    OnClick = BitBtn2Click
  end
end
