object frmplus: Tfrmplus
  Left = 114
  Top = 98
  Width = 649
  Height = 356
  BorderIcons = [biSystemMenu]
  Caption = '新增工序'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 63
    Top = 56
    Width = 26
    Height = 13
    Caption = '車種'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label2: TLabel
    Left = 37
    Top = 56
    Width = 52
    Height = 13
    Caption = '工序序號'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label3: TLabel
    Left = 262
    Top = 56
    Width = 52
    Height = 13
    Caption = '工序代號'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label4: TLabel
    Left = 37
    Top = 88
    Width = 52
    Height = 13
    Caption = '工序名稱'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label5: TLabel
    Left = 457
    Top = 88
    Width = 60
    Height = 13
    Caption = '時間(小時)'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label6: TLabel
    Left = 235
    Top = 120
    Width = 79
    Height = 13
    Caption = '標準TMU單價'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label7: TLabel
    Left = 465
    Top = 120
    Width = 52
    Height = 13
    Caption = '建議單價'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label8: TLabel
    Left = 37
    Top = 152
    Width = 52
    Height = 13
    Caption = '車針型號'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label9: TLabel
    Left = 220
    Top = 152
    Width = 94
    Height = 13
    Caption = '運針間針步(3cm)'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label10: TLabel
    Left = 491
    Top = 152
    Width = 26
    Height = 13
    Caption = '面線'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label11: TLabel
    Left = 63
    Top = 184
    Width = 26
    Height = 13
    Caption = '底線'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label12: TLabel
    Left = 228
    Top = 184
    Width = 86
    Height = 13
    Caption = '子口尺寸(車縫)'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label13: TLabel
    Left = 444
    Top = 184
    Width = 73
    Height = 13
    Caption = '子口尺寸(折)'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label14: TLabel
    Left = 16
    Top = 216
    Width = 73
    Height = 13
    Caption = '子口尺寸(疊)'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label15: TLabel
    Left = 288
    Top = 216
    Width = 26
    Height = 13
    Caption = '針距'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label16: TLabel
    Left = 491
    Top = 216
    Width = 26
    Height = 13
    Caption = '振幅'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label17: TLabel
    Left = 37
    Top = 248
    Width = 52
    Height = 13
    Caption = '縫紉要點'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label19: TLabel
    Left = 37
    Top = 120
    Width = 52
    Height = 13
    Caption = '標準單價'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label20: TLabel
    Left = 465
    Top = 56
    Width = 52
    Height = 13
    Caption = '車種代號'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label18: TLabel
    Left = 37
    Top = 16
    Width = 52
    Height = 13
    Caption = '工序來源'
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
  end
  object Label21: TLabel
    Left = 360
    Top = 8
    Width = 3
    Height = 13
    Visible = False
  end
  object DBEdit1: TDBEdit
    Left = 318
    Top = 54
    Width = 91
    Height = 21
    DataField = 'Dh'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
  end
  object DBEdit2: TDBEdit
    Left = 91
    Top = 86
    Width = 206
    Height = 21
    DataField = 'Mc'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 4
  end
  object DBEdit3: TDBEdit
    Left = 520
    Top = 86
    Width = 105
    Height = 21
    DataField = 'Sj'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
  end
  object DBEdit4: TDBEdit
    Left = 318
    Top = 118
    Width = 93
    Height = 21
    Color = clWhite
    DataField = 'Dj1'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 7
  end
  object DBEdit5: TDBEdit
    Left = 520
    Top = 118
    Width = 105
    Height = 21
    DataField = 'Dj2'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
  end
  object DBEdit6: TDBEdit
    Left = 91
    Top = 150
    Width = 94
    Height = 21
    DataField = 'Czxh'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 9
  end
  object DBEdit7: TDBEdit
    Left = 318
    Top = 150
    Width = 93
    Height = 21
    DataField = 'Yzjzb'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 10
  end
  object DBEdit8: TDBEdit
    Left = 520
    Top = 150
    Width = 105
    Height = 21
    DataField = 'Mx'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 11
  end
  object DBEdit9: TDBEdit
    Left = 91
    Top = 182
    Width = 94
    Height = 21
    DataField = 'Dx'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 12
  end
  object DBEdit10: TDBEdit
    Left = 318
    Top = 182
    Width = 93
    Height = 21
    DataField = 'Cfzkcc'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 13
  end
  object DBEdit11: TDBEdit
    Left = 520
    Top = 182
    Width = 105
    Height = 21
    DataField = 'Zzkcc'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 14
  end
  object DBEdit12: TDBEdit
    Left = 91
    Top = 214
    Width = 94
    Height = 21
    DataField = 'Dzkcc'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 15
  end
  object DBEdit13: TDBEdit
    Left = 318
    Top = 214
    Width = 93
    Height = 21
    DataField = 'Zj'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 16
  end
  object DBEdit14: TDBEdit
    Left = 520
    Top = 214
    Width = 105
    Height = 21
    DataField = 'Zf'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 17
  end
  object DBEdit15: TDBEdit
    Left = 91
    Top = 246
    Width = 534
    Height = 21
    DataField = 'Fryd'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 18
  end
  object DBEdit17: TDBEdit
    Left = 91
    Top = 118
    Width = 94
    Height = 21
    DataField = 'Bzdj'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
  end
  object DBEdit18: TDBEdit
    Left = 520
    Top = 54
    Width = 105
    Height = 21
    DataField = 'Czbh'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
  end
  object DBEdit19: TDBEdit
    Left = 91
    Top = 54
    Width = 70
    Height = 21
    DataField = 'Seq'
    DataSource = DataSource1
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
  end
  object ComboBox1: TComboBox
    Left = 91
    Top = 14
    Width = 206
    Height = 21
    Font.Charset = CHINESEBIG5_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = '新細明體'
    Font.Style = []
    ItemHeight = 13
    ParentFont = False
    TabOrder = 0
    OnChange = ComboBox1Change
  end
  object DBNavigator1: TDBNavigator
    Left = 24
    Top = 288
    Width = 180
    Height = 30
    DataSource = DataSource1
    VisibleButtons = [nbFirst, nbPrior, nbNext, nbLast, nbInsert, nbPost]
    TabOrder = 19
  end
  object BitBtn3: TBitBtn
    Left = 204
    Top = 288
    Width = 30
    Height = 30
    Hint = '退出'
    ParentShowHint = False
    ShowHint = True
    TabOrder = 20
    OnClick = BitBtn3Click
    Glyph.Data = {
      76010000424D7601000000000000760000002800000020000000100000000100
      04000000000000010000120B0000120B00001000000000000000000000000000
      800000800000008080008000000080008000808000007F7F7F00BFBFBF000000
      FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00330000000000
      03333377777777777F333301BBBBBBBB033333773F3333337F3333011BBBBBBB
      0333337F73F333337F33330111BBBBBB0333337F373F33337F333301110BBBBB
      0333337F337F33337F333301110BBBBB0333337F337F33337F333301110BBBBB
      0333337F337F33337F333301110BBBBB0333337F337F33337F333301110BBBBB
      0333337F337F33337F333301110BBBBB0333337F337FF3337F33330111B0BBBB
      0333337F337733337F333301110BBBBB0333337F337F33337F333301110BBBBB
      0333337F3F7F33337F333301E10BBBBB0333337F7F7F33337F333301EE0BBBBB
      0333337F777FFFFF7F3333000000000003333377777777777333}
    NumGlyphs = 2
  end
  object DataSource1: TDataSource
    Left = 448
    Top = 8
  end
  object Query1: TClientDataSet
    Aggregates = <>
    Params = <>
    ProviderName = 'dspphg'
    RemoteServer = frmxtdl.SocketConnection1
    Left = 368
    Top = 16
  end
  object Query2: TClientDataSet
    Aggregates = <>
    Params = <>
    ProviderName = 'dspphg'
    RemoteServer = frmxtdl.SocketConnection1
    Left = 408
    Top = 8
  end
end
