//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8806
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.MobileQC.BO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=PH.MobileQC_Offline;Persist Security Inf" +
            "o=True;;User ID=sa;Password=teamwork")]
        public string PH_MobileQC_OfflineConnectionString {
            get {
                return ((string)(this["PH_MobileQC_OfflineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.MobileQC;User ID=sa")]
        public string PH_MobileQCConnectionString1 {
            get {
                return ((string)(this["PH_MobileQCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.MobileQC;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string PH_MobileQCConnectionString {
            get {
                return ((string)(this["PH_MobileQCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.MobileQC;Persist Security Info=Tru" +
            "e;User ID=sa;Password=teamwork")]
        public string PH_MobileQCConnectionString2 {
            get {
                return ((string)(this["PH_MobileQCConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.FabricInspection;User ID=sa")]
        public string PH_FabricInspectionConnectionString {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240;Initial Catalog=PH.MobileQC;User ID=itsys;Password=uatadm1" +
            "n")]
        public string PH_MobileQCConnectionString3 {
            get {
                return ((string)(this["PH_MobileQCConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.MobileQC;User ID=ituser")]
        public string PH_MobileQCConnectionString4 {
            get {
                return ((string)(this["PH_MobileQCConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10\\sqlserver2005;Initial Catalog=PH.MobileQC;Persist Security " +
            "Info=True;User ID=ituser;Password=itsystem@2009")]
        public string PH_MobileQCConnectionString5 {
            get {
                return ((string)(this["PH_MobileQCConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.MobileQC;Persist Security Info=True;User" +
            " ID=Ituser;Password=itsystem@2009")]
        public string PH_MobileQCConnectionString6 {
            get {
                return ((string)(this["PH_MobileQCConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PH.MobileQC;Persist Security I" +
            "nfo=True;User ID=ituser;Password=itsystem@2009")]
        public string PH_MobileQCConnectionString7 {
            get {
                return ((string)(this["PH_MobileQCConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PH.MobileQC;Persist Security I" +
            "nfo=True;User ID=ituser")]
        public string PH_MobileQCConnectionString8 {
            get {
                return ((string)(this["PH_MobileQCConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10\\sqlserver2005;Initial Catalog=PH.LWPM.WP;Persist Security I" +
            "nfo=True;User ID=ituser")]
        public string PH_LWPM_WPConnectionString {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.MobileQC;Persist Security Info=True;User" +
            " ID=ituser;Password=itsystem@2009")]
        public string PH_MobileQCConnectionString9 {
            get {
                return ((string)(this["PH_MobileQCConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.MobileQC;User ID=ituser;Password=itsyste" +
            "m@2009")]
        public string PH_MobileQCConnectionString10 {
            get {
                return ((string)(this["PH_MobileQCConnectionString10"]));
            }
        }
    }
}
