//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QEFullInspetion.Models.PH_MobileQC
{

    [DeferredDeletion(false)]
    public partial class FullInspectionRight : XPObject
    {
        string fUserID;
        [Indexed(@"RightObject;RightType", Name = @"Index_UserRight")]
        public string UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<string>(nameof(UserID), ref fUserID, value); }
        }
        string fRightObject;
        [Size(300)]
        public string RightObject
        {
            get { return fRightObject; }
            set { SetPropertyValue<string>(nameof(RightObject), ref fRightObject, value); }
        }
        string fRightType;
        public string RightType
        {
            get { return fRightType; }
            set { SetPropertyValue<string>(nameof(RightType), ref fRightType, value); }
        }
    }

}
