//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QEFullInspetion.Models.PH_MobileQC
{

    public partial class FullInspectionHeader : XPLiteObject
    {
        long fOid;
        [Key(true)]
        public long Oid
        {
            get { return fOid; }
            set { SetPropertyValue<long>(nameof(Oid), ref fOid, value); }
        }
        string fFactory;
        [Size(10)]
        public string Factory
        {
            get { return fFactory; }
            set { SetPropertyValue<string>(nameof(Factory), ref fFactory, value); }
        }
        string fWorkShop;
        [Size(20)]
        public string WorkShop
        {
            get { return fWorkShop; }
            set { SetPropertyValue<string>(nameof(WorkShop), ref fWorkShop, value); }
        }
        string fLine;
        [Size(20)]
        public string Line
        {
            get { return fLine; }
            set { SetPropertyValue<string>(nameof(Line), ref fLine, value); }
        }
        string fProject;
        [Size(20)]
        public string Project
        {
            get { return fProject; }
            set { SetPropertyValue<string>(nameof(Project), ref fProject, value); }
        }
        string fLWO;
        [Size(50)]
        public string LWO
        {
            get { return fLWO; }
            set { SetPropertyValue<string>(nameof(LWO), ref fLWO, value); }
        }
        int? fQNQty;
        public int? QNQty
        {
            get { return fQNQty; }
            set { SetPropertyValue<int?>(nameof(QNQty), ref fQNQty, value); }
        }
        string fInspectionConfirmBy;
        public string InspectionConfirmBy
        {
            get { return fInspectionConfirmBy; }
            set { SetPropertyValue<string>(nameof(InspectionConfirmBy), ref fInspectionConfirmBy, value); }
        }
        string fColorCode;
        [Size(20)]
        public string ColorCode
        {
            get { return fColorCode; }
            set { SetPropertyValue<string>(nameof(ColorCode), ref fColorCode, value); }
        }
        string fStyleNo;
        [Size(50)]
        public string StyleNo
        {
            get { return fStyleNo; }
            set { SetPropertyValue<string>(nameof(StyleNo), ref fStyleNo, value); }
        }
        string fSeqNo;
        [Size(20)]
        public string SeqNo
        {
            get { return fSeqNo; }
            set { SetPropertyValue<string>(nameof(SeqNo), ref fSeqNo, value); }
        }
        DateTime fInspectionDate;
        public DateTime InspectionDate
        {
            get { return fInspectionDate; }
            set { SetPropertyValue<DateTime>(nameof(InspectionDate), ref fInspectionDate, value); }
        }
        string fInspector;
        public string Inspector
        {
            get { return fInspector; }
            set { SetPropertyValue<string>(nameof(Inspector), ref fInspector, value); }
        }
        string fLineLeader;
        public string LineLeader
        {
            get { return fLineLeader; }
            set { SetPropertyValue<string>(nameof(LineLeader), ref fLineLeader, value); }
        }
        string fLineLeaderSignature;
        public string LineLeaderSignature
        {
            get { return fLineLeaderSignature; }
            set { SetPropertyValue<string>(nameof(LineLeaderSignature), ref fLineLeaderSignature, value); }
        }
        string fSewingSupervisior;
        public string SewingSupervisior
        {
            get { return fSewingSupervisior; }
            set { SetPropertyValue<string>(nameof(SewingSupervisior), ref fSewingSupervisior, value); }
        }
        string fRemark;
        [Size(2000)]
        public string Remark
        {
            get { return fRemark; }
            set { SetPropertyValue<string>(nameof(Remark), ref fRemark, value); }
        }
        DateTime? fExftyDate;
        public DateTime? ExftyDate
        {
            get { return fExftyDate; }
            set { SetPropertyValue<DateTime?>(nameof(ExftyDate), ref fExftyDate, value); }
        }
        [Association(@"FullInspectionDetailReferencesFullInspectionHeader")]
        public XPCollection<FullInspectionDetail> FullInspectionDetails { get { return GetCollection<FullInspectionDetail>(nameof(FullInspectionDetails)); } }
    }

}
