//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QEFullInspetion.Models.PH_MobileQC
{

    public partial class FullInspectionDetail : XPLiteObject
    {
        long fOid;
        [Key(true)]
        public long Oid
        {
            get { return fOid; }
            set { SetPropertyValue<long>(nameof(Oid), ref fOid, value); }
        }
        FullInspectionHeader fFullInspectionHeader;
        [Association(@"FullInspectionDetailReferencesFullInspectionHeader")]
        public FullInspectionHeader FullInspectionHeader
        {
            get { return fFullInspectionHeader; }
            set { SetPropertyValue<FullInspectionHeader>(nameof(FullInspectionHeader), ref fFullInspectionHeader, value); }
        }
        int? fBoxNo;
        public int? BoxNo
        {
            get { return fBoxNo; }
            set { SetPropertyValue<int?>(nameof(BoxNo), ref fBoxNo, value); }
        }
        string fSize;
        [Size(20)]
        public string Size
        {
            get { return fSize; }
            set { SetPropertyValue<string>(nameof(Size), ref fSize, value); }
        }
        int? fProductQty;
        public int? ProductQty
        {
            get { return fProductQty; }
            set { SetPropertyValue<int?>(nameof(ProductQty), ref fProductQty, value); }
        }
        int? fDefectiveGarmentQty;
        public int? DefectiveGarmentQty
        {
            get { return fDefectiveGarmentQty; }
            set { SetPropertyValue<int?>(nameof(DefectiveGarmentQty), ref fDefectiveGarmentQty, value); }
        }
        decimal? fDefectiveGarmentPercent;
        public decimal? DefectiveGarmentPercent
        {
            get { return fDefectiveGarmentPercent; }
            set { SetPropertyValue<decimal?>(nameof(DefectiveGarmentPercent), ref fDefectiveGarmentPercent, value); }
        }
        string fRejectStage;
        [Size(20)]
        public string RejectStage
        {
            get { return fRejectStage; }
            set { SetPropertyValue<string>(nameof(RejectStage), ref fRejectStage, value); }
        }
        int? fDefectQty;
        public int? DefectQty
        {
            get { return fDefectQty; }
            set { SetPropertyValue<int?>(nameof(DefectQty), ref fDefectQty, value); }
        }
        bool? fRepaired;
        public bool? Repaired
        {
            get { return fRepaired; }
            set { SetPropertyValue<bool?>(nameof(Repaired), ref fRepaired, value); }
        }
        string fCheckPointSigned;
        [Size(200)]
        public string CheckPointSigned
        {
            get { return fCheckPointSigned; }
            set { SetPropertyValue<string>(nameof(CheckPointSigned), ref fCheckPointSigned, value); }
        }
        DateTime? fInspectionDate;
        public DateTime? InspectionDate
        {
            get { return fInspectionDate; }
            set { SetPropertyValue<DateTime?>(nameof(InspectionDate), ref fInspectionDate, value); }
        }
        string fInspector;
        public string Inspector
        {
            get { return fInspector; }
            set { SetPropertyValue<string>(nameof(Inspector), ref fInspector, value); }
        }
        string fPODCode1;
        [Size(20)]
        public string PODCode1
        {
            get { return fPODCode1; }
            set { SetPropertyValue<string>(nameof(PODCode1), ref fPODCode1, value); }
        }
        string fPODNameEN1;
        [Size(500)]
        public string PODNameEN1
        {
            get { return fPODNameEN1; }
            set { SetPropertyValue<string>(nameof(PODNameEN1), ref fPODNameEN1, value); }
        }
        string fPODNameCN1;
        [Size(500)]
        public string PODNameCN1
        {
            get { return fPODNameCN1; }
            set { SetPropertyValue<string>(nameof(PODNameCN1), ref fPODNameCN1, value); }
        }
        string fPODNameBD1;
        [Size(500)]
        public string PODNameBD1
        {
            get { return fPODNameBD1; }
            set { SetPropertyValue<string>(nameof(PODNameBD1), ref fPODNameBD1, value); }
        }
        string fPODCode2;
        [Size(20)]
        public string PODCode2
        {
            get { return fPODCode2; }
            set { SetPropertyValue<string>(nameof(PODCode2), ref fPODCode2, value); }
        }
        string fPODNameEN2;
        [Size(500)]
        public string PODNameEN2
        {
            get { return fPODNameEN2; }
            set { SetPropertyValue<string>(nameof(PODNameEN2), ref fPODNameEN2, value); }
        }
        string fPODNameCN2;
        [Size(500)]
        public string PODNameCN2
        {
            get { return fPODNameCN2; }
            set { SetPropertyValue<string>(nameof(PODNameCN2), ref fPODNameCN2, value); }
        }
        string fPODNameBD2;
        [Size(500)]
        public string PODNameBD2
        {
            get { return fPODNameBD2; }
            set { SetPropertyValue<string>(nameof(PODNameBD2), ref fPODNameBD2, value); }
        }
        string fPODCode3;
        [Size(20)]
        public string PODCode3
        {
            get { return fPODCode3; }
            set { SetPropertyValue<string>(nameof(PODCode3), ref fPODCode3, value); }
        }
        string fPODNameEN3;
        [Size(500)]
        public string PODNameEN3
        {
            get { return fPODNameEN3; }
            set { SetPropertyValue<string>(nameof(PODNameEN3), ref fPODNameEN3, value); }
        }
        string fPODNameCN3;
        [Size(500)]
        public string PODNameCN3
        {
            get { return fPODNameCN3; }
            set { SetPropertyValue<string>(nameof(PODNameCN3), ref fPODNameCN3, value); }
        }
        string fPODNameBD3;
        [Size(500)]
        public string PODNameBD3
        {
            get { return fPODNameBD3; }
            set { SetPropertyValue<string>(nameof(PODNameBD3), ref fPODNameBD3, value); }
        }
        string fDefectCode1;
        [Size(20)]
        public string DefectCode1
        {
            get { return fDefectCode1; }
            set { SetPropertyValue<string>(nameof(DefectCode1), ref fDefectCode1, value); }
        }
        string fDefectNameEN1;
        [Size(500)]
        public string DefectNameEN1
        {
            get { return fDefectNameEN1; }
            set { SetPropertyValue<string>(nameof(DefectNameEN1), ref fDefectNameEN1, value); }
        }
        string fDefectNameCN1;
        [Size(500)]
        public string DefectNameCN1
        {
            get { return fDefectNameCN1; }
            set { SetPropertyValue<string>(nameof(DefectNameCN1), ref fDefectNameCN1, value); }
        }
        string fDefectNameBD1;
        [Size(500)]
        public string DefectNameBD1
        {
            get { return fDefectNameBD1; }
            set { SetPropertyValue<string>(nameof(DefectNameBD1), ref fDefectNameBD1, value); }
        }
        string fDefectCode2;
        [Size(20)]
        public string DefectCode2
        {
            get { return fDefectCode2; }
            set { SetPropertyValue<string>(nameof(DefectCode2), ref fDefectCode2, value); }
        }
        string fDefectNameEN2;
        [Size(500)]
        public string DefectNameEN2
        {
            get { return fDefectNameEN2; }
            set { SetPropertyValue<string>(nameof(DefectNameEN2), ref fDefectNameEN2, value); }
        }
        string fDefectNameCN2;
        [Size(500)]
        public string DefectNameCN2
        {
            get { return fDefectNameCN2; }
            set { SetPropertyValue<string>(nameof(DefectNameCN2), ref fDefectNameCN2, value); }
        }
        string fDefectNameBD2;
        [Size(500)]
        public string DefectNameBD2
        {
            get { return fDefectNameBD2; }
            set { SetPropertyValue<string>(nameof(DefectNameBD2), ref fDefectNameBD2, value); }
        }
        string fDefectCode3;
        [Size(20)]
        public string DefectCode3
        {
            get { return fDefectCode3; }
            set { SetPropertyValue<string>(nameof(DefectCode3), ref fDefectCode3, value); }
        }
        string fDefectNameEN3;
        [Size(500)]
        public string DefectNameEN3
        {
            get { return fDefectNameEN3; }
            set { SetPropertyValue<string>(nameof(DefectNameEN3), ref fDefectNameEN3, value); }
        }
        string fDefectNameCN3;
        [Size(500)]
        public string DefectNameCN3
        {
            get { return fDefectNameCN3; }
            set { SetPropertyValue<string>(nameof(DefectNameCN3), ref fDefectNameCN3, value); }
        }
        string fDefectNameBD3;
        [Size(500)]
        public string DefectNameBD3
        {
            get { return fDefectNameBD3; }
            set { SetPropertyValue<string>(nameof(DefectNameBD3), ref fDefectNameBD3, value); }
        }
        int? fPODQty;
        public int? PODQty
        {
            get { return fPODQty; }
            set { SetPropertyValue<int?>(nameof(PODQty), ref fPODQty, value); }
        }
        int? fRejectQty;
        public int? RejectQty
        {
            get { return fRejectQty; }
            set { SetPropertyValue<int?>(nameof(RejectQty), ref fRejectQty, value); }
        }
    }

}
