//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QEFullInspetion.Models.PH_MobileQC
{

    [NonPersistent]
    public partial class sp_GetFullInspectionHeaderResult
    {
        public long Oid { get; set; }
        public string Factory { get; set; }
        public string WorkShop { get; set; }
        public string Line { get; set; }
        public string Project { get; set; }
        public string LWO { get; set; }
        public string ColorCode { get; set; }
        public string StyleNo { get; set; }
        public string SeqNo { get; set; }
        public bool InspectionCompleted { get; set; }
        public int QNQty { get; set; }
        public string InspectionConfirmBy { get; set; }
        public DateTime InspectionDate { get; set; }
        public string Inspector { get; set; }
        public string LineLeader { get; set; }
        public string LineLeaderSignature { get; set; }
        public string SewingSupervisior { get; set; }
        public string Remark { get; set; }
    }

}
