//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QEFullInspetion.Models.PH_MobileQC
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData Execsp_GetFullInspectionIncompleteList(Session session)
        {
            return session.ExecuteSproc("sp_GetFullInspectionIncompleteList");
        }
    }
}
