//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.LWPM.BO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\Test;Initial Catalog=PH.LWPM.WP;Persist Security Info=True" +
            ";User ID=sa")]
        public string PH_LWPM_WPConnectionString1 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\TEST;Initial Catalog=PH.LWPM.WP;Persist Security Info=True" +
            ";User ID=sa;Password=teamwork")]
        public string PH_LWPM_WPConnectionString2 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10\\sqlserver2005;Initial Catalog=PH.LWPM.WP;Persist Security I" +
            "nfo=True;User ID=ituser;Password=itsystem@2009")]
        public string PH_LWPM_WPConnectionString3 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.LWPM.WP;Persist Security Info=True" +
            ";User ID=sa;Password=teamwork")]
        public string PH_LWPM_WPConnectionString4 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240;Initial Catalog=PH.LWPM.WP;Persist Security Info=True;User" +
            " ID=itsys;Password=uatadm1n")]
        public string PH_LWPM_WPConnectionString5 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.LWPM.WP;User ID=ituser;Password=itsystem" +
            "@2009")]
        public string PH_LWPM_WPConnectionString6 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.LWPM.WP;Persist Security Info=True;User " +
            "ID=ituser;Password=itsystem@2009")]
        public string PH_LWPM_WPConnectionString7 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240;Initial Catalog=PH.LWPM.WP;Persist Security Info=True;User" +
            " ID=itsys")]
        public string PH_LWPM_WPConnectionString8 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10\\sqlserver2005;Initial Catalog=PH.LWPM.WP;User ID=ituser")]
        public string PH_LWPM_WPConnectionString9 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10\\sqlserver2005;Initial Catalog=PH.LWPM.WP;Persist Security I" +
            "nfo=True;User ID=ituser")]
        public string PH_LWPM_WPConnectionString10 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240;Initial Catalog=PH.LWPM.WP;User ID=itsys;Password=uatadm1n" +
            "")]
        public string PH_LWPM_WPConnectionString11 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10\\sqlserver2005;Initial Catalog=PH.LWPM.WP;Persist Security I" +
            "nfo=True;User ID=ituser;Password=itsystem@2009")]
        public string PH_LWPM_WPConnectionString {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10\\sqlserver2005;Initial Catalog=PH.LWPM.WP;User ID=ituser;Pas" +
            "sword=itsystem@2009")]
        public string PH_LWPM_WPConnectionString12 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.LWPM.WP;User ID=ituser")]
        public string PH_LWPM_WPConnectionString13 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.LWPM.WP;Persist Security Info=True;User " +
            "ID=ituser")]
        public string PH_LWPM_WPConnectionString14 {
            get {
                return ((string)(this["PH_LWPM_WPConnectionString14"]));
            }
        }
    }
}
