unit printu;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ppBands, ppCtrls, ppStrtch, ppRegion, ppPrnabl, ppClass,
  ppCache, ppProd, ppReport, ppComm, ppRelatv, ppDB, ppDBPipe, ppDBBDE, Db,
  DBTables, StdCtrls, ExtCtrls, Buttons, myChkBox,dbclient,ppViewr;
type
  Tfrmprint = class(TForm)
    xx1: TCheckBox;
    xx2: TCheckBox;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    Label1: TLabel;
    DataSource1: TDataSource;
    DataSource2: TDataSource;
    ppBDEPipeline1: TppBDEPipeline;
    ppBDEPipeline2: TppBDEPipeline;
    ppReport1: TppReport;
    ppReport2: TppReport;
    ppLabel1: TppLabel;
    ppLabel2: TppLabel;
    ppDBText1: TppDBText;
    ppLabel3: TppLabel;
    ppDBText2: TppDBText;
    ppLabel4: TppLabel;
    ppDBText3: TppDBText;
    ppRegion1: TppRegion;
    ppSummaryBand1: TppSummaryBand;
    ppLabel5: TppLabel;
    ppLabel6: TppLabel;
    ppLabel7: TppLabel;
    ppShape1: TppShape;
    ppShape2: TppShape;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppLabel11: TppLabel;
    ppLabel12: TppLabel;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLine1: TppLine;
    ppLine2: TppLine;
    ppShape3: TppShape;
    ppLabel17: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppLabel20: TppLabel;
    ppLabel21: TppLabel;
    ppLabel22: TppLabel;
    ppShape4: TppShape;
    ppShape5: TppShape;
    ppShape6: TppShape;
    ppShape7: TppShape;
    ppShape8: TppShape;
    ppShape9: TppShape;
    ppShape10: TppShape;
    ppShape11: TppShape;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppLabel25: TppLabel;
    ppRegion2: TppRegion;
    ppShape12: TppShape;
    ppDBText4: TppDBText;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppShape13: TppShape;
    ppShape14: TppShape;
    ppShape15: TppShape;
    ppRegion3: TppRegion;
    ppLabel26: TppLabel;
    ppShape16: TppShape;
    ppShape17: TppShape;
    ppShape18: TppShape;
    ppShape19: TppShape;
    ppShape20: TppShape;
    ppShape21: TppShape;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppDBText23: TppDBText;
    ppDBText24: TppDBText;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppDBText27: TppDBText;
    ppDBText28: TppDBText;
    ppDBText29: TppDBText;
    ppDBText30: TppDBText;
    ppDBText31: TppDBText;
    ppDBText32: TppDBText;
    ppDBText33: TppDBText;
    ppDBText34: TppDBText;
    ppDBText35: TppDBText;
    ppDBText36: TppDBText;
    ppDBText37: TppDBText;
    ppDBText38: TppDBText;
    ppDBText39: TppDBText;
    ppDBText40: TppDBText;
    ppDBText41: TppDBText;
    ppDBText42: TppDBText;
    ppDBText43: TppDBText;
    ppDBText44: TppDBText;
    ppDBText45: TppDBText;
    ppDBText46: TppDBText;
    ppDBText47: TppDBText;
    ppDBText48: TppDBText;
    ppDBText49: TppDBText;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppDBText52: TppDBText;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppDBText55: TppDBText;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBText58: TppDBText;
    ppReport3: TppReport;
    ppHeaderBand3: TppHeaderBand;
    ppLabel27: TppLabel;
    ppLabel28: TppLabel;
    ppDBText59: TppDBText;
    ppLabel29: TppLabel;
    ppDBText60: TppDBText;
    ppLabel30: TppLabel;
    ppDBText61: TppDBText;
    ppRegion4: TppRegion;
    ppShape22: TppShape;
    ppShape23: TppShape;
    ppShape24: TppShape;
    ppShape25: TppShape;
    ppShape26: TppShape;
    ppShape27: TppShape;
    ppShape28: TppShape;
    ppShape29: TppShape;
    ppShape30: TppShape;
    ppShape31: TppShape;
    ppLabel31: TppLabel;
    ppLabel32: TppLabel;
    ppLabel33: TppLabel;
    ppShape32: TppShape;
    ppLabel34: TppLabel;
    ppLabel35: TppLabel;
    ppLabel36: TppLabel;
    ppLabel37: TppLabel;
    ppLabel38: TppLabel;
    ppLabel39: TppLabel;
    ppLabel40: TppLabel;
    ppLabel41: TppLabel;
    ppLabel42: TppLabel;
    ppLine3: TppLine;
    ppLine4: TppLine;
    ppLabel43: TppLabel;
    ppLabel44: TppLabel;
    ppLabel45: TppLabel;
    ppLabel46: TppLabel;
    ppLabel47: TppLabel;
    ppLabel48: TppLabel;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppDBText64: TppDBText;
    ppDBText65: TppDBText;
    ppDBText66: TppDBText;
    ppDBText67: TppDBText;
    ppDBText68: TppDBText;
    ppDBText69: TppDBText;
    ppDBText70: TppDBText;
    ppDBText71: TppDBText;
    ppDBText72: TppDBText;
    ppDBText73: TppDBText;
    ppDBText74: TppDBText;
    ppDBText75: TppDBText;
    ppDBText76: TppDBText;
    ppDBText77: TppDBText;
    ppDBText78: TppDBText;
    ppDBText79: TppDBText;
    ppDBText80: TppDBText;
    ppDBText81: TppDBText;
    ppDBText82: TppDBText;
    ppDBText83: TppDBText;
    ppDBText84: TppDBText;
    ppDBText85: TppDBText;
    ppDBText86: TppDBText;
    ppDBText87: TppDBText;
    ppDBText88: TppDBText;
    ppDBText89: TppDBText;
    ppDBText90: TppDBText;
    ppDBText91: TppDBText;
    ppDBText92: TppDBText;
    ppDBText93: TppDBText;
    ppDetailBand3: TppDetailBand;
    ppRegion5: TppRegion;
    ppShape33: TppShape;
    ppDBText94: TppDBText;
    ldwz: TppDBText;
    ppShape34: TppShape;
    ppShape35: TppShape;
    ppShape36: TppShape;
    ppShape37: TppShape;
    ppShape38: TppShape;
    ppShape39: TppShape;
    ppShape40: TppShape;
    ppShape41: TppShape;
    ppShape42: TppShape;
    ppDBText97: TppDBText;
    ppDBText98: TppDBText;
    ppDBText99: TppDBText;
    ppDBText100: TppDBText;
    ppDBText101: TppDBText;
    ppDBText102: TppDBText;
    ppDBText103: TppDBText;
    ppDBText104: TppDBText;
    ppDBText105: TppDBText;
    ppDBText106: TppDBText;
    ppDBText107: TppDBText;
    ppDBText108: TppDBText;
    ppDBText109: TppDBText;
    ppDBText110: TppDBText;
    ppDBText111: TppDBText;
    ppDBText112: TppDBText;
    ppDBText113: TppDBText;
    ppDBText114: TppDBText;
    ppDBText115: TppDBText;
    ppFooterBand3: TppFooterBand;
    ppLabel49: TppLabel;
    ppLabel50: TppLabel;
    ppLabel51: TppLabel;
    ppSummaryBand2: TppSummaryBand;
    ppRegion6: TppRegion;
    ppLabel52: TppLabel;
    ppDBText116: TppDBText;
    ppLabel53: TppLabel;
    ppLabel54: TppLabel;
    ppDBText95: TppDBText;
    ppLabel55: TppLabel;
    ppDBText96: TppDBText;
    ppLabel56: TppLabel;
    ppDBText117: TppDBText;
    ppLabel57: TppLabel;
    ppDBText118: TppDBText;
    ppLabel58: TppLabel;
    ppDBText119: TppDBText;
    ppLabel59: TppLabel;
    ppDBText120: TppDBText;
    ppRegion7: TppRegion;
    ppShape43: TppShape;
    ppShape44: TppShape;
    ppLine5: TppLine;
    ppRegion8: TppRegion;
    ppDBText121: TppDBText;
    ppLabel60: TppLabel;
    ppLabel61: TppLabel;
    ppLabel62: TppLabel;
    ppLabel63: TppLabel;
    myDBCheckBox1: TmyDBCheckBox;
    ppLabel64: TppLabel;
    myDBCheckBox2: TmyDBCheckBox;
    ppLabel65: TppLabel;
    ppLabel66: TppLabel;
    myDBCheckBox3: TmyDBCheckBox;
    ppLabel67: TppLabel;
    myDBCheckBox4: TmyDBCheckBox;
    ppLabel68: TppLabel;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppLabel71: TppLabel;
    ppLabel72: TppLabel;
    ppLabel73: TppLabel;
    ppLabel74: TppLabel;
    ppLabel75: TppLabel;
    ppLabel76: TppLabel;
    ppLabel77: TppLabel;
    ppLabel78: TppLabel;
    ppLabel79: TppLabel;
    ppShape45: TppShape;
    ppShape46: TppShape;
    ppLabel80: TppLabel;
    ppLabel81: TppLabel;
    ppLabel82: TppLabel;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    ppLabel85: TppLabel;
    ppLabel86: TppLabel;
    ppLabel87: TppLabel;
    ppLine6: TppLine;
    ppLine7: TppLine;
    ppShape47: TppShape;
    ppShape48: TppShape;
    ppShape49: TppShape;
    ppSummaryBand3: TppSummaryBand;
    ppRegion9: TppRegion;
    ppLabel88: TppLabel;
    ppLabel89: TppLabel;
    ppLabel90: TppLabel;
    ppLabel91: TppLabel;
    ppLabel92: TppLabel;
    ppShape50: TppShape;
    ppDBText122: TppDBText;
    ppDBText123: TppDBText;
    ppShape51: TppShape;
    ppShape52: TppShape;
    ppShape53: TppShape;
    ppShape54: TppShape;
    ppShape55: TppShape;
    ppShape56: TppShape;
    ppShape63: TppShape;
    ppShape64: TppShape;
    ppShape65: TppShape;
    ppDBText124: TppDBText;
    ppDBText125: TppDBText;
    ppDBText126: TppDBText;
    ppDBText127: TppDBText;
    ppDBText128: TppDBText;
    ppDBText129: TppDBText;
    ppDBText130: TppDBText;
    ppDBText131: TppDBText;
    ppDBText132: TppDBText;
    ppDBText133: TppDBText;
    ppDBText134: TppDBText;
    ppDBText135: TppDBText;
    ppDBText136: TppDBText;
    ppDBText137: TppDBText;
    ppDBText138: TppDBText;
    ppDBText139: TppDBText;
    ppDBText140: TppDBText;
    ppDBText141: TppDBText;
    ppDBText142: TppDBText;
    ppDBText143: TppDBText;
    ppDBText144: TppDBText;
    ppDBText145: TppDBText;
    ppDBText146: TppDBText;
    ppDBText147: TppDBText;
    ppDBText148: TppDBText;
    ppDBText149: TppDBText;
    ppShape66: TppShape;
    ppDBText150: TppDBText;
    ppShape67: TppShape;
    ppShape68: TppShape;
    ppShape69: TppShape;
    ppShape70: TppShape;
    ppShape71: TppShape;
    ppShape72: TppShape;
    ppShape73: TppShape;
    ppShape74: TppShape;
    ppShape75: TppShape;
    ppShape76: TppShape;
    ppShape77: TppShape;
    ppShape78: TppShape;
    ppShape79: TppShape;
    ppDBText151: TppDBText;
    ppDBText152: TppDBText;
    ppDBText153: TppDBText;
    ppDBText154: TppDBText;
    ppDBText155: TppDBText;
    ppDBText156: TppDBText;
    ppDBText157: TppDBText;
    ppDBText158: TppDBText;
    ppDBText159: TppDBText;
    ppDBText160: TppDBText;
    ppDBText161: TppDBText;
    ppDBText162: TppDBText;
    ppDBText163: TppDBText;
    ppDBText164: TppDBText;
    ppDBText165: TppDBText;
    ppDBText166: TppDBText;
    ppDBText167: TppDBText;
    ppDBText168: TppDBText;
    ppDBText169: TppDBText;
    ppDBText170: TppDBText;
    ppDBText171: TppDBText;
    ppDBText172: TppDBText;
    ppDBText173: TppDBText;
    ppDBText174: TppDBText;
    ppReport4: TppReport;
    ppHeaderBand4: TppHeaderBand;
    ppLabel94: TppLabel;
    ppLabel95: TppLabel;
    ppDBText175: TppDBText;
    ppLabel96: TppLabel;
    ppDBText176: TppDBText;
    ppLabel97: TppLabel;
    ppDBText177: TppDBText;
    ppLabel98: TppLabel;
    ppDBText178: TppDBText;
    ppLabel99: TppLabel;
    ppDBText179: TppDBText;
    ppLabel100: TppLabel;
    ppDBText180: TppDBText;
    ppRegion10: TppRegion;
    ppShape84: TppShape;
    ppShape85: TppShape;
    ppShape86: TppShape;
    ppShape87: TppShape;
    ppShape88: TppShape;
    ppShape89: TppShape;
    ppShape90: TppShape;
    ppShape91: TppShape;
    ppLine8: TppLine;
    ppLabel101: TppLabel;
    ppLabel102: TppLabel;
    ppLabel103: TppLabel;
    ppLabel104: TppLabel;
    myDBCheckBox5: TmyDBCheckBox;
    ppLabel105: TppLabel;
    myDBCheckBox6: TmyDBCheckBox;
    ppLabel106: TppLabel;
    ppLabel107: TppLabel;
    myDBCheckBox7: TmyDBCheckBox;
    ppLabel108: TppLabel;
    myDBCheckBox8: TmyDBCheckBox;
    ppLabel109: TppLabel;
    ppLabel110: TppLabel;
    ppLabel111: TppLabel;
    ppLabel112: TppLabel;
    ppLabel113: TppLabel;
    ppLabel114: TppLabel;
    ppLabel115: TppLabel;
    ppLabel116: TppLabel;
    ppLabel117: TppLabel;
    ppLabel118: TppLabel;
    ppLabel119: TppLabel;
    ppLabel120: TppLabel;
    ppLabel121: TppLabel;
    ppLabel122: TppLabel;
    ppLabel123: TppLabel;
    ppLabel124: TppLabel;
    ppLabel125: TppLabel;
    ppLabel126: TppLabel;
    ppLabel127: TppLabel;
    ppLabel128: TppLabel;
    ppLine9: TppLine;
    ppLine10: TppLine;
    ppShape92: TppShape;
    ppShape93: TppShape;
    ppShape94: TppShape;
    ppShape95: TppShape;
    ppShape96: TppShape;
    ppShape99: TppShape;
    ppDBText181: TppDBText;
    ppDBText182: TppDBText;
    ppDBText183: TppDBText;
    ppDBText184: TppDBText;
    ppDBText185: TppDBText;
    ppDBText186: TppDBText;
    ppDBText187: TppDBText;
    ppDBText188: TppDBText;
    ppDBText189: TppDBText;
    ppDBText190: TppDBText;
    ppDBText191: TppDBText;
    ppDBText192: TppDBText;
    ppDBText193: TppDBText;
    ppDBText194: TppDBText;
    ppDBText195: TppDBText;
    ppDBText196: TppDBText;
    ppDBText197: TppDBText;
    ppDBText198: TppDBText;
    ppDBText199: TppDBText;
    ppDBText200: TppDBText;
    ppDBText201: TppDBText;
    ppDBText202: TppDBText;
    ppDBText203: TppDBText;
    ppDBText204: TppDBText;
    ppShape100: TppShape;
    ppDetailBand4: TppDetailBand;
    ppRegion11: TppRegion;
    ppDBText205: TppDBText;
    ppShape101: TppShape;
    ldwz1: TppDBText;
    ppShape102: TppShape;
    ppDBText208: TppDBText;
    mthd4: TppDBText;
    ppShape103: TppShape;
    ppDBText210: TppDBText;
    ppShape104: TppShape;
    ppShape105: TppShape;
    ppShape106: TppShape;
    ppShape107: TppShape;
    ppShape108: TppShape;
    ppShape109: TppShape;
    ppShape110: TppShape;
    ppShape111: TppShape;
    ppShape112: TppShape;
    ppShape113: TppShape;
    ppShape114: TppShape;
    ppShape115: TppShape;
    ppShape116: TppShape;
    ppDBText211: TppDBText;
    ppDBText212: TppDBText;
    ppDBText213: TppDBText;
    ppDBText214: TppDBText;
    ppDBText215: TppDBText;
    ppDBText216: TppDBText;
    ppDBText217: TppDBText;
    ppDBText218: TppDBText;
    ppDBText219: TppDBText;
    ppDBText220: TppDBText;
    ppDBText221: TppDBText;
    ppDBText222: TppDBText;
    ppDBText223: TppDBText;
    ppDBText224: TppDBText;
    ppDBText225: TppDBText;
    ppDBText226: TppDBText;
    ppDBText227: TppDBText;
    ppDBText228: TppDBText;
    ppDBText229: TppDBText;
    ppDBText230: TppDBText;
    ppDBText231: TppDBText;
    ppDBText232: TppDBText;
    ppDBText233: TppDBText;
    ppDBText234: TppDBText;
    ppFooterBand4: TppFooterBand;
    ppLabel130: TppLabel;
    ppLabel131: TppLabel;
    ppLabel132: TppLabel;
    ppLabel133: TppLabel;
    ppSummaryBand4: TppSummaryBand;
    ppRegion12: TppRegion;
    ppLabel134: TppLabel;
    ppDBText207: TppDBText;
    ppDBText235: TppDBText;
    ppDBText206: TppDBText;
    ppDBText236: TppDBText;
    ppDBText237: TppDBText;
    ppDBText238: TppDBText;
    RadioGroup1: TRadioGroup;
    ppLabel93: TppLabel;
    ppLine11: TppLine;
    ppLabel129: TppLabel;
    ppLine12: TppLine;
    ppLabel135: TppLabel;
    ppLine13: TppLine;
    ppLabel136: TppLabel;
    ppLine14: TppLine;
    ppReport5: TppReport;
    ppHeaderBand5: TppHeaderBand;
    ppLabel137: TppLabel;
    ppLabel138: TppLabel;
    ppDBText239: TppDBText;
    ppLabel139: TppLabel;
    ppDBText240: TppDBText;
    ppLabel140: TppLabel;
    ppDBText241: TppDBText;
    ppLabel141: TppLabel;
    ppDBText242: TppDBText;
    ppLabel142: TppLabel;
    ppDBText243: TppDBText;
    ppLabel143: TppLabel;
    ppDBText244: TppDBText;
    ppRegion13: TppRegion;
    ppShape118: TppShape;
    ppShape119: TppShape;
    ppShape121: TppShape;
    ppShape122: TppShape;
    ppShape123: TppShape;
    ppShape124: TppShape;
    ppShape129: TppShape;
    ppShape130: TppShape;
    ppShape131: TppShape;
    ppShape132: TppShape;
    ppShape133: TppShape;
    ppShape134: TppShape;
    ppLine15: TppLine;
    ppLabel144: TppLabel;
    ppLabel145: TppLabel;
    ppLabel146: TppLabel;
    ppLabel147: TppLabel;
    myDBCheckBox9: TmyDBCheckBox;
    ppLabel148: TppLabel;
    myDBCheckBox10: TmyDBCheckBox;
    ppLabel149: TppLabel;
    ppLabel150: TppLabel;
    myDBCheckBox11: TmyDBCheckBox;
    ppLabel151: TppLabel;
    myDBCheckBox12: TmyDBCheckBox;
    ppLabel152: TppLabel;
    ppLabel153: TppLabel;
    ppLabel154: TppLabel;
    ppLabel155: TppLabel;
    ppLabel156: TppLabel;
    ppLabel157: TppLabel;
    ppLabel158: TppLabel;
    ppLabel159: TppLabel;
    ppLabel160: TppLabel;
    ppLabel161: TppLabel;
    ppLabel162: TppLabel;
    ppLabel163: TppLabel;
    ppLabel164: TppLabel;
    ppLabel165: TppLabel;
    ppLabel166: TppLabel;
    ppLabel167: TppLabel;
    ppLabel168: TppLabel;
    ppLabel169: TppLabel;
    ppLabel170: TppLabel;
    ppLabel171: TppLabel;
    ppLine16: TppLine;
    ppLine17: TppLine;
    ppShape135: TppShape;
    ppShape136: TppShape;
    ppDBText245: TppDBText;
    ppDBText246: TppDBText;
    ppDBText247: TppDBText;
    ppDBText248: TppDBText;
    ppDBText249: TppDBText;
    ppDBText250: TppDBText;
    ppDBText251: TppDBText;
    ppDBText252: TppDBText;
    ppDBText253: TppDBText;
    ppDBText254: TppDBText;
    ppDBText255: TppDBText;
    ppDBText256: TppDBText;
    ppDBText257: TppDBText;
    ppDBText258: TppDBText;
    ppDBText259: TppDBText;
    ppDBText260: TppDBText;
    ppDBText261: TppDBText;
    ppDBText262: TppDBText;
    ppDBText263: TppDBText;
    ppDBText264: TppDBText;
    ppDBText265: TppDBText;
    ppDBText266: TppDBText;
    ppDBText267: TppDBText;
    ppDBText268: TppDBText;
    ppShape137: TppShape;
    ppLabel172: TppLabel;
    ppLine18: TppLine;
    ppDetailBand5: TppDetailBand;
    ppRegion14: TppRegion;
    ppShape138: TppShape;
    ppShape139: TppShape;
    ppDBText269: TppDBText;
    ppShape140: TppShape;
    ppDBText270: TppDBText;
    ppDBText271: TppDBText;
    ppShape141: TppShape;
    ppDBText272: TppDBText;
    ppDBText273: TppDBText;
    ppShape142: TppShape;
    ppDBText274: TppDBText;
    ppShape143: TppShape;
    ppShape144: TppShape;
    ppShape145: TppShape;
    ppShape146: TppShape;
    ppShape147: TppShape;
    ppShape148: TppShape;
    ppShape149: TppShape;
    ppShape150: TppShape;
    ppShape151: TppShape;
    ppShape152: TppShape;
    ppShape153: TppShape;
    ppDBText275: TppDBText;
    ppDBText276: TppDBText;
    ppDBText277: TppDBText;
    ppDBText278: TppDBText;
    ppDBText279: TppDBText;
    ppDBText280: TppDBText;
    ppDBText281: TppDBText;
    ppDBText282: TppDBText;
    ppDBText283: TppDBText;
    ppDBText284: TppDBText;
    ppDBText285: TppDBText;
    ppDBText286: TppDBText;
    ppDBText287: TppDBText;
    ppDBText288: TppDBText;
    ppDBText289: TppDBText;
    ppDBText290: TppDBText;
    ppDBText291: TppDBText;
    ppDBText292: TppDBText;
    ppDBText293: TppDBText;
    ppDBText294: TppDBText;
    ppDBText295: TppDBText;
    ppDBText296: TppDBText;
    ppDBText297: TppDBText;
    ppDBText298: TppDBText;
    ppDBText299: TppDBText;
    ppDBText300: TppDBText;
    ppFooterBand5: TppFooterBand;
    ppLabel173: TppLabel;
    ppLabel174: TppLabel;
    ppLabel175: TppLabel;
    ppLabel176: TppLabel;
    ppSummaryBand5: TppSummaryBand;
    ppRegion15: TppRegion;
    ppLabel177: TppLabel;
    ppDBText301: TppDBText;
    ppReport6: TppReport;
    ppHeaderBand6: TppHeaderBand;
    ppLabel178: TppLabel;
    ppLabel179: TppLabel;
    ppDBText302: TppDBText;
    ppLabel180: TppLabel;
    ppDBText303: TppDBText;
    ppLabel181: TppLabel;
    ppDBText304: TppDBText;
    ppLabel182: TppLabel;
    ppDBText305: TppDBText;
    ppLabel183: TppLabel;
    ppDBText306: TppDBText;
    ppLabel184: TppLabel;
    ppDBText307: TppDBText;
    ppRegion16: TppRegion;
    ppShape155: TppShape;
    ppShape156: TppShape;
    ppShape158: TppShape;
    ppShape159: TppShape;
    ppShape160: TppShape;
    ppShape161: TppShape;
    ppShape166: TppShape;
    ppShape167: TppShape;
    ppShape168: TppShape;
    ppShape169: TppShape;
    ppShape170: TppShape;
    ppShape171: TppShape;
    ppLine19: TppLine;
    ppLabel185: TppLabel;
    ppLabel186: TppLabel;
    ppLabel187: TppLabel;
    ppLabel188: TppLabel;
    myDBCheckBox13: TmyDBCheckBox;
    ppLabel189: TppLabel;
    myDBCheckBox14: TmyDBCheckBox;
    ppLabel190: TppLabel;
    ppLabel191: TppLabel;
    myDBCheckBox15: TmyDBCheckBox;
    ppLabel192: TppLabel;
    myDBCheckBox16: TmyDBCheckBox;
    ppLabel193: TppLabel;
    ppLabel194: TppLabel;
    ppLabel195: TppLabel;
    ppLabel196: TppLabel;
    ppLabel197: TppLabel;
    ppLabel198: TppLabel;
    ppLabel199: TppLabel;
    ppLabel200: TppLabel;
    ppLabel201: TppLabel;
    ppLabel202: TppLabel;
    ppLabel203: TppLabel;
    ppLabel204: TppLabel;
    ppLabel205: TppLabel;
    ppLabel206: TppLabel;
    ppLabel207: TppLabel;
    ppLabel208: TppLabel;
    ppLabel209: TppLabel;
    ppLabel210: TppLabel;
    ppLabel211: TppLabel;
    ppLabel212: TppLabel;
    ppLine20: TppLine;
    ppLine21: TppLine;
    ppShape172: TppShape;
    ppShape173: TppShape;
    ppDBText308: TppDBText;
    ppDBText309: TppDBText;
    ppDBText310: TppDBText;
    ppDBText311: TppDBText;
    ppDBText312: TppDBText;
    ppDBText313: TppDBText;
    ppDBText314: TppDBText;
    ppDBText315: TppDBText;
    ppDBText316: TppDBText;
    ppDBText317: TppDBText;
    ppDBText318: TppDBText;
    ppDBText319: TppDBText;
    ppDBText320: TppDBText;
    ppDBText321: TppDBText;
    ppDBText322: TppDBText;
    ppDBText323: TppDBText;
    ppDBText324: TppDBText;
    ppDBText325: TppDBText;
    ppDBText326: TppDBText;
    ppDBText327: TppDBText;
    ppDBText328: TppDBText;
    ppDBText329: TppDBText;
    ppDBText330: TppDBText;
    ppDBText331: TppDBText;
    ppShape174: TppShape;
    ppLabel213: TppLabel;
    ppLine22: TppLine;
    ppDetailBand6: TppDetailBand;
    ppRegion17: TppRegion;
    ppShape175: TppShape;
    ppShape176: TppShape;
    ppDBText332: TppDBText;
    ppShape177: TppShape;
    ldwz2: TppDBText;
    ppShape178: TppShape;
    ppDBText335: TppDBText;
    mthd6: TppDBText;
    ppShape179: TppShape;
    ppDBText337: TppDBText;
    ppShape180: TppShape;
    ppShape181: TppShape;
    ppShape182: TppShape;
    ppShape183: TppShape;
    ppShape184: TppShape;
    ppShape185: TppShape;
    ppShape186: TppShape;
    ppShape187: TppShape;
    ppShape188: TppShape;
    ppShape189: TppShape;
    ppShape190: TppShape;
    ppDBText338: TppDBText;
    ppDBText339: TppDBText;
    ppDBText340: TppDBText;
    ppDBText341: TppDBText;
    ppDBText342: TppDBText;
    ppDBText343: TppDBText;
    ppDBText344: TppDBText;
    ppDBText345: TppDBText;
    ppDBText346: TppDBText;
    ppDBText347: TppDBText;
    ppDBText348: TppDBText;
    ppDBText349: TppDBText;
    ppDBText350: TppDBText;
    ppDBText351: TppDBText;
    ppDBText352: TppDBText;
    ppDBText353: TppDBText;
    ppDBText354: TppDBText;
    ppDBText355: TppDBText;
    ppDBText356: TppDBText;
    ppDBText357: TppDBText;
    ppDBText358: TppDBText;
    ppDBText359: TppDBText;
    ppDBText360: TppDBText;
    ppDBText361: TppDBText;
    ppDBText362: TppDBText;
    ppDBText363: TppDBText;
    ppFooterBand6: TppFooterBand;
    ppLabel214: TppLabel;
    ppLabel215: TppLabel;
    ppLabel216: TppLabel;
    ppLabel217: TppLabel;
    ppSummaryBand6: TppSummaryBand;
    ppRegion18: TppRegion;
    ppLabel218: TppLabel;
    ppDBText364: TppDBText;
    ppReport7: TppReport;
    ppHeaderBand7: TppHeaderBand;
    ppLabel219: TppLabel;
    ppLabel220: TppLabel;
    ppDBText333: TppDBText;
    ppLabel221: TppLabel;
    ppDBText334: TppDBText;
    ppLabel222: TppLabel;
    ppDBText365: TppDBText;
    ppLabel223: TppLabel;
    ppDBText366: TppDBText;
    ppLabel224: TppLabel;
    ppDBText367: TppDBText;
    ppLabel225: TppLabel;
    ppDBText368: TppDBText;
    ppRegion19: TppRegion;
    ppShape192: TppShape;
    ppShape193: TppShape;
    ppShape195: TppShape;
    ppShape196: TppShape;
    ppShape197: TppShape;
    ppShape198: TppShape;
    ppShape203: TppShape;
    ppShape204: TppShape;
    ppShape205: TppShape;
    ppShape206: TppShape;
    ppShape207: TppShape;
    ppShape208: TppShape;
    ppLine23: TppLine;
    ppLabel226: TppLabel;
    ppLabel227: TppLabel;
    ppLabel228: TppLabel;
    ppLabel229: TppLabel;
    myDBCheckBox17: TmyDBCheckBox;
    ppLabel230: TppLabel;
    myDBCheckBox18: TmyDBCheckBox;
    ppLabel231: TppLabel;
    ppLabel232: TppLabel;
    myDBCheckBox19: TmyDBCheckBox;
    ppLabel233: TppLabel;
    myDBCheckBox20: TmyDBCheckBox;
    ppLabel234: TppLabel;
    ppLabel235: TppLabel;
    ppLabel236: TppLabel;
    ppLabel237: TppLabel;
    ppLabel238: TppLabel;
    ppLabel239: TppLabel;
    ppLabel240: TppLabel;
    ppLabel241: TppLabel;
    ppLabel242: TppLabel;
    ppLabel243: TppLabel;
    ppLabel244: TppLabel;
    ppLabel245: TppLabel;
    ppLabel246: TppLabel;
    ppLabel247: TppLabel;
    ppLabel248: TppLabel;
    ppLabel249: TppLabel;
    ppLabel250: TppLabel;
    ppLabel251: TppLabel;
    ppLabel252: TppLabel;
    ppLabel253: TppLabel;
    ppLine24: TppLine;
    ppLine25: TppLine;
    ppShape209: TppShape;
    ppShape210: TppShape;
    ppDBText369: TppDBText;
    ppDBText370: TppDBText;
    ppDBText371: TppDBText;
    ppDBText372: TppDBText;
    ppDBText373: TppDBText;
    ppDBText374: TppDBText;
    ppDBText375: TppDBText;
    ppDBText376: TppDBText;
    ppDBText377: TppDBText;
    ppDBText378: TppDBText;
    ppDBText379: TppDBText;
    ppDBText380: TppDBText;
    ppDBText381: TppDBText;
    ppDBText382: TppDBText;
    ppDBText383: TppDBText;
    ppDBText384: TppDBText;
    ppDBText385: TppDBText;
    ppDBText386: TppDBText;
    ppDBText387: TppDBText;
    ppDBText388: TppDBText;
    ppDBText389: TppDBText;
    ppDBText390: TppDBText;
    ppDBText391: TppDBText;
    ppDBText392: TppDBText;
    ppShape211: TppShape;
    ppLabel254: TppLabel;
    ppLine26: TppLine;
    ppDetailBand7: TppDetailBand;
    ppRegion20: TppRegion;
    ppShape212: TppShape;
    ppShape213: TppShape;
    ppDBText393: TppDBText;
    ppShape214: TppShape;
    ppDBText394: TppDBText;
    ppDBText395: TppDBText;
    ppShape215: TppShape;
    ppDBText396: TppDBText;
    ppDBText397: TppDBText;
    ppShape216: TppShape;
    ppDBText398: TppDBText;
    ppShape217: TppShape;
    ppShape218: TppShape;
    ppShape219: TppShape;
    ppShape220: TppShape;
    ppShape221: TppShape;
    ppShape222: TppShape;
    ppShape223: TppShape;
    ppShape224: TppShape;
    ppShape225: TppShape;
    ppShape226: TppShape;
    ppShape227: TppShape;
    ppDBText399: TppDBText;
    ppDBText400: TppDBText;
    ppDBText401: TppDBText;
    ppDBText402: TppDBText;
    ppDBText403: TppDBText;
    ppDBText404: TppDBText;
    ppDBText405: TppDBText;
    ppDBText406: TppDBText;
    ppDBText407: TppDBText;
    ppDBText408: TppDBText;
    ppDBText409: TppDBText;
    ppDBText410: TppDBText;
    ppDBText411: TppDBText;
    ppDBText412: TppDBText;
    ppDBText413: TppDBText;
    ppDBText414: TppDBText;
    ppDBText415: TppDBText;
    ppDBText416: TppDBText;
    ppDBText417: TppDBText;
    ppDBText418: TppDBText;
    ppDBText419: TppDBText;
    ppDBText420: TppDBText;
    ppDBText421: TppDBText;
    ppDBText422: TppDBText;
    ppDBText423: TppDBText;
    ppDBText424: TppDBText;
    ppFooterBand7: TppFooterBand;
    ppLabel255: TppLabel;
    ppLabel256: TppLabel;
    ppLabel257: TppLabel;
    ppLabel258: TppLabel;
    ppSummaryBand7: TppSummaryBand;
    ppRegion21: TppRegion;
    ppLabel259: TppLabel;
    ppDBText425: TppDBText;
    ppReport8: TppReport;
    ppHeaderBand8: TppHeaderBand;
    ppLabel260: TppLabel;
    ppLabel261: TppLabel;
    ppDBText426: TppDBText;
    ppLabel262: TppLabel;
    ppDBText427: TppDBText;
    ppLabel263: TppLabel;
    ppDBText428: TppDBText;
    ppLabel264: TppLabel;
    ppDBText429: TppDBText;
    ppLabel265: TppLabel;
    ppDBText430: TppDBText;
    ppLabel266: TppLabel;
    ppDBText431: TppDBText;
    ppRegion22: TppRegion;
    ppShape229: TppShape;
    ppShape230: TppShape;
    ppShape232: TppShape;
    ppShape233: TppShape;
    ppShape234: TppShape;
    ppShape235: TppShape;
    ppShape240: TppShape;
    ppShape241: TppShape;
    ppShape242: TppShape;
    ppShape243: TppShape;
    ppShape244: TppShape;
    ppShape245: TppShape;
    ppLine27: TppLine;
    ppLabel267: TppLabel;
    ppLabel268: TppLabel;
    ppLabel269: TppLabel;
    ppLabel270: TppLabel;
    myDBCheckBox21: TmyDBCheckBox;
    ppLabel271: TppLabel;
    myDBCheckBox22: TmyDBCheckBox;
    ppLabel272: TppLabel;
    ppLabel273: TppLabel;
    myDBCheckBox23: TmyDBCheckBox;
    ppLabel274: TppLabel;
    myDBCheckBox24: TmyDBCheckBox;
    ppLabel275: TppLabel;
    ppLabel276: TppLabel;
    ppLabel277: TppLabel;
    ppLabel278: TppLabel;
    ppLabel279: TppLabel;
    ppLabel280: TppLabel;
    ppLabel281: TppLabel;
    ppLabel282: TppLabel;
    ppLabel283: TppLabel;
    ppLabel284: TppLabel;
    ppLabel285: TppLabel;
    ppLabel286: TppLabel;
    ppLabel287: TppLabel;
    ppLabel288: TppLabel;
    ppLabel289: TppLabel;
    ppLabel290: TppLabel;
    ppLabel291: TppLabel;
    ppLabel292: TppLabel;
    ppLabel293: TppLabel;
    ppLabel294: TppLabel;
    ppLine28: TppLine;
    ppLine29: TppLine;
    ppShape246: TppShape;
    ppShape247: TppShape;
    ppDBText432: TppDBText;
    ppDBText433: TppDBText;
    ppDBText434: TppDBText;
    ppDBText435: TppDBText;
    ppDBText436: TppDBText;
    ppDBText437: TppDBText;
    ppDBText438: TppDBText;
    ppDBText439: TppDBText;
    ppDBText440: TppDBText;
    ppDBText441: TppDBText;
    ppDBText442: TppDBText;
    ppDBText443: TppDBText;
    ppDBText444: TppDBText;
    ppDBText445: TppDBText;
    ppDBText446: TppDBText;
    ppDBText447: TppDBText;
    ppDBText448: TppDBText;
    ppDBText449: TppDBText;
    ppDBText450: TppDBText;
    ppDBText451: TppDBText;
    ppDBText452: TppDBText;
    ppDBText453: TppDBText;
    ppDBText454: TppDBText;
    ppDBText455: TppDBText;
    ppShape248: TppShape;
    ppLabel295: TppLabel;
    ppLine30: TppLine;
    ppDetailBand8: TppDetailBand;
    ppRegion23: TppRegion;
    ppShape249: TppShape;
    ppShape250: TppShape;
    ppDBText456: TppDBText;
    ppShape251: TppShape;
    ldwz3: TppDBText;
    ppShape252: TppShape;
    ppDBText459: TppDBText;
    mthd8: TppDBText;
    ppShape253: TppShape;
    ppDBText461: TppDBText;
    ppShape254: TppShape;
    ppShape255: TppShape;
    ppShape256: TppShape;
    ppShape257: TppShape;
    ppShape258: TppShape;
    ppShape259: TppShape;
    ppShape260: TppShape;
    ppShape261: TppShape;
    ppShape262: TppShape;
    ppShape263: TppShape;
    ppShape264: TppShape;
    ppDBText462: TppDBText;
    ppDBText463: TppDBText;
    ppDBText464: TppDBText;
    ppDBText465: TppDBText;
    ppDBText466: TppDBText;
    ppDBText467: TppDBText;
    ppDBText468: TppDBText;
    ppDBText469: TppDBText;
    ppDBText470: TppDBText;
    ppDBText471: TppDBText;
    ppDBText472: TppDBText;
    ppDBText473: TppDBText;
    ppDBText474: TppDBText;
    ppDBText475: TppDBText;
    ppDBText476: TppDBText;
    ppDBText477: TppDBText;
    ppDBText478: TppDBText;
    ppDBText479: TppDBText;
    ppDBText480: TppDBText;
    ppDBText481: TppDBText;
    ppDBText482: TppDBText;
    ppDBText483: TppDBText;
    ppDBText484: TppDBText;
    ppDBText485: TppDBText;
    ppDBText486: TppDBText;
    ppDBText487: TppDBText;
    ppFooterBand8: TppFooterBand;
    ppLabel296: TppLabel;
    ppLabel297: TppLabel;
    ppLabel298: TppLabel;
    ppLabel299: TppLabel;
    ppSummaryBand8: TppSummaryBand;
    ppRegion24: TppRegion;
    ppLabel300: TppLabel;
    ppDBText488: TppDBText;
    ppLabel301: TppLabel;
    Query1: TClientDataSet;
    Query2: TClientDataSet;
    Query3: TClientDataSet;
    procedure BitBtn2Click(Sender: TObject);
    procedure FormDeactivate(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure BitBtn1Click(Sender: TObject);
    procedure ppReport1PreviewFormCreate(Sender: TObject);
    procedure ppReport3PreviewFormCreate(Sender: TObject);
    procedure ppReport2PreviewFormCreate(Sender: TObject);
    procedure ppReport4PreviewFormCreate(Sender: TObject);
    procedure ppReport5PreviewFormCreate(Sender: TObject);
    procedure ppReport6PreviewFormCreate(Sender: TObject);
    procedure ppReport7PreviewFormCreate(Sender: TObject);
    procedure ppReport8PreviewFormCreate(Sender: TObject);
    procedure ppDetailBand1BeforePrint(Sender: TObject);
    procedure ppDetailBand3BeforePrint(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmprint: Tfrmprint;

implementation
uses siztblu, sampletblu;
{$R *.DFM}

procedure Tfrmprint.BitBtn2Click(Sender: TObject);
begin
  close;
end;

procedure Tfrmprint.FormDeactivate(Sender: TObject);
begin
  close;
end;

procedure Tfrmprint.FormShow(Sender: TObject);
begin
  xx1.checked:=true;
  xx2.checked:=true;
end;

procedure Tfrmprint.BitBtn1Click(Sender: TObject);
begin
 if radiogroup1.ItemIndex=0 then
 begin
  if xx1.checked=true then
  begin
    if xx2.checked=true then
    begin
      if label1.caption='siztbl' then
      begin
        query1.close;
        query1.params.clear;
        query1.params.createparam(ftstring,'stylno',ptinput);
        query1.commandtext:='select a.cdate,a.mdate,a.mem,b.*,c.* from SZ_lsize a,SZ_lsize1 b,SZ_lsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno';
//        query1.prepare;
        query1.params[0].asstring:=frmsiztbl.table1.fieldbyname('stylno').value;
        query1.open;
        if query1.recordcount>0 then
        begin
          ppline12.visible:=false;
          pplabel129.Visible:=false;
          ppreport1.print;
        end;
      end
      else
      begin
        query2.close;
        query2.params.clear;
        query2.params.createparam(ftstring,'stylno',ptinput);
        query2.commandtext:='select a.custn,a.cstyl,a.mdate,a.mem,a.cprov,a.pprov,b.*,c.* from SZ_sampsize a,SZ_sampsize1 b,SZ_sampsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno';
//        query2.prepare;
        query2.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
        query2.open;
        if query2.recordcount>0 then
        begin
          ppline14.visible:=false;
          pplabel136.Visible:=false;
          ppreport2.print;
          query3.close;
          query3.params.clear;
          query3.params.createparam(ftstring,'stylno',ptinput);          
          query3.commandtext:='select size13,size25 from SZ_sampsize2 where stylno=:stylno';
//          query3.prepare;
          query3.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
          query3.open;
          if not query3.fieldbyname('size13').isnull then
          begin
            ppline18.visible:=false;
            pplabel172.visible:=false;
            ppreport5.print;
            if not query3.fieldbyname('size25').isnull then
            begin
             ppline26.visible:=true;
             pplabel254.visible:=true;
             ppreport7.print;
            end;
          end;
        end;
      end;
    end
    else
    begin
      if label1.caption='siztbl' then
      begin
        query1.close;
        query1.params.clear;
        query1.params.createparam(ftstring,'stylno',ptinput);
        query1.commandtext:='select a.cdate,a.mdate,a.mem,b.*,c.* from SZ_lsize a,SZ_lsize1 b,SZ_lsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno';
//        query1.prepare;
        query1.params[0].asstring:=frmsiztbl.table1.fieldbyname('stylno').value;
        query1.open;
        if query1.recordcount>0 then
        begin
          ppline11.visible:=false;
          pplabel93.Visible:=false;
          ldwz.DataField:='cmeas';
          ppreport3.print;
        end;
      end
      else
      begin
        query2.close;
        query2.params.clear;
        query2.params.createparam(ftstring,'stylno',ptinput);
        query2.commandtext:='select a.custn,a.cstyl,a.mdate,a.mem,a.cprov,a.pprov,b.*,c.* from SZ_sampsize a,SZ_sampsize1 b,SZ_sampsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno';
//        query2.prepare;
        query2.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
        query2.open;
        if query2.recordcount>0 then
        begin
          ppline13.visible:=false;
          pplabel135.Visible:=false;
          ldwz1.datafield:='cmeas';
          mthd4.datafield:='methd';
          ppreport4.print;
          query3.close;
          query3.params.clear;
          query3.params.createparam(ftstring,'stylno',ptinput);          
          query3.commandtext:='select size13,size25 from SZ_sampsize2 where stylno=:stylno';
//          query3.prepare;
          query3.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
          query3.open;
          if not query3.fieldbyname('size13').isnull then
          begin
            ppline22.visible:=false;
            pplabel213.visible:=false;
            ldwz2.datafield:='cmeas';
            mthd6.datafield:='methd';
            ppreport6.print;
            if not query3.fieldbyname('size25').isnull then
            begin
             ppline30.visible:=true;
             pplabel295.visible:=true;
             ldwz3.datafield:='cmeas';
             mthd8.datafield:='methd';
             ppreport8.print;
            end;
          end;
        end;
      end;
    end;
  end
  else
  begin
    if xx2.checked=true then
    begin
      if label1.caption='siztbl' then
      begin
        query1.close;
        query1.params.clear;
        query1.params.createparam(ftstring,'stylno',ptinput);
        query1.commandtext:='select a.cdate,a.mdate,a.mem,b.*,c.* from SZ_lsize a,SZ_lsize1 b,SZ_lsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno';
//        query1.prepare;
        query1.params[0].asstring:=frmsiztbl.table1.fieldbyname('stylno').value;
        query1.open;
        if query1.recordcount>0 then
        begin
          ppline11.visible:=false;
          pplabel93.Visible:=false;
          ldwz.datafield:='emeas';
          ppreport3.print;
        end;
      end
      else
      begin
        query2.close;
        query2.params.clear;
        query2.params.createparam(ftstring,'stylno',ptinput);        
        query2.commandtext:='select a.custn,a.cstyl,a.mdate,a.mem,a.pprov,a.cprov,b.*,c.* from SZ_sampsize a,SZ_sampsize1 b,SZ_sampsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno';
//        query2.prepare;
        query2.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
        query2.open;
        if query2.recordcount>0 then
        begin
          ppline13.visible:=false;
          pplabel135.Visible:=false;
          ldwz1.datafield:='emeas';
          mthd4.datafield:='emethd';
          ppreport4.print;
          query3.close;
          query3.params.clear;
          query3.params.createparam(ftstring,'stylno',ptinput);          
          query3.commandtext:='select size13,size25 from SZ_sampsize2 where stylno=:stylno';
//          query3.prepare;
          query3.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
          query3.open;
          if not query3.fieldbyname('size13').isnull then
          begin
            ppline22.visible:=false;
            pplabel213.visible:=false;
            ldwz2.datafield:='emeas';
            mthd6.datafield:='emethd';
            ppreport6.print;
            if not query3.fieldbyname('size25').isnull then
            begin
             ppline30.visible:=false;
             pplabel295.visible:=false;
             ldwz3.datafield:='emeas';
             mthd8.datafield:='emethd';
             ppreport8.print;
            end;
          end;
        end;
      end;
    end;
  end;
 end
 else
 begin
  if xx1.checked=true then
  begin
    if xx2.checked=true then
    begin
      if label1.caption='siztbl' then
      begin
        query1.close;
        query1.params.clear;
        query1.params.createparam(ftstring,'stylno',ptinput);
        query1.commandtext:='select a.cdate,a.mdate,a.mem,b.*,c.* from SZ_lsize a,SZ_lsize1 b,SZ_lsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno and b.flg1=1';
//        query1.prepare;
        query1.params[0].asstring:=frmsiztbl.table1.fieldbyname('stylno').value;
        query1.open;
        if query1.recordcount>0 then
        begin
          ppline12.visible:=true;
          pplabel129.Visible:=true;
          ppreport1.print;
        end;
      end
      else
      begin
        query2.close;
        query2.params.clear;
        query2.params.createparam(ftstring,'stylno',ptinput);        
        query2.commandtext:='select a.custn,a.cstyl,a.mdate,a.mem,a.cprov,a.pprov,b.*,c.* from SZ_sampsize a,SZ_sampsize1 b,SZ_sampsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno and b.kh=1';
//        query2.prepare;
        query2.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
        query2.open;
        if query2.recordcount>0 then
        begin
          ppline14.visible:=true;
          pplabel136.Visible:=true;
          ppreport2.print;
          query3.close;
          query3.params.clear;
          query3.params.createparam(ftstring,'stylno',ptinput);          
          query3.commandtext:='select size13,size25 from SZ_sampsize2 where stylno=:stylno';
//          query3.prepare;
          query3.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
          query3.open;
          if not query3.fieldbyname('size13').isnull then
          begin
            ppline18.visible:=true;
            pplabel172.visible:=true;
            ppreport5.print;
            if not query3.fieldbyname('size25').isnull then
            begin
             ppline26.visible:=true;
             pplabel254.visible:=true;
             ppreport7.print;
            end;
          end;
        end;
      end;
    end
    else
    begin
      if label1.caption='siztbl' then
      begin
        query1.close;
        query1.params.clear;
        query1.params.createparam(ftstring,'stylno',ptinput);
        query1.commandtext:='select a.cdate,a.mdate,a.mem,b.*,c.* from SZ_lsize a,SZ_lsize1 b,SZ_lsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno and b.flg1=1';
//        query1.prepare;
        query1.params[0].asstring:=frmsiztbl.table1.fieldbyname('stylno').value;
        query1.open;
        if query1.recordcount>0 then
        begin
          ppline11.visible:=true;
          pplabel93.Visible:=true;
          ldwz.DataField:='cmeas';
          ppreport3.print;
        end;
      end
      else
      begin
        query2.close;
        query2.params.clear;
        query2.params.createparam(ftstring,'stylno',ptinput);
        query2.commandtext:='select a.custn,a.cstyl,a.mdate,a.mem,a.cprov,a.pprov,b.*,c.* from SZ_sampsize a,SZ_sampsize1 b,SZ_sampsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno and b.kh=1';
//        query2.prepare;
        query2.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
        query2.open;
        if query2.recordcount>0 then
        begin
          ppline13.visible:=true;
          pplabel135.Visible:=true;
          ldwz1.datafield:='cmeas';
          mthd4.datafield:='methd';
          ppreport4.print;
          query3.close;
          query3.params.clear;
          query3.params.createparam(ftstring,'stylno',ptinput);          
          query3.commandtext:='select size13,size25 from SZ_sampsize2 where stylno=:stylno';
//          query3.prepare;
          query3.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
          query3.open;
          if not query3.fieldbyname('size13').isnull then
          begin
            ppline22.visible:=true;
            pplabel213.visible:=true;
            ldwz2.datafield:='cmeas';
            mthd6.datafield:='methd';
            ppreport6.print;
            if not query3.fieldbyname('size25').isnull then
            begin
             ppline30.visible:=true;
             pplabel295.visible:=true;
             ldwz3.datafield:='cmeas';
             mthd8.datafield:='methd';
             ppreport8.print;
            end;
          end;
        end;
      end;
    end;
  end
  else
  begin
    if xx2.checked=true then
    begin
      if label1.caption='siztbl' then
      begin
        query1.close;
        query1.params.clear;
        query1.params.createparam(ftstring,'stylno',ptinput);
        query1.commandtext:='select a.cdate,a.mdate,a.mem,b.*,c.* from SZ_lsize a,SZ_lsize1 b,SZ_lsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno and b.flg1=1';
//        query1.prepare;
        query1.params[0].asstring:=frmsiztbl.table1.fieldbyname('stylno').value;
        query1.open;
        if query1.recordcount>0 then
        begin
          ppline11.visible:=true;
          pplabel93.Visible:=true;
          ldwz.datafield:='emeas';
          ppreport3.print;
        end;
      end
      else
      begin
        query2.close;
        query2.params.clear;
        query2.params.createparam(ftstring,'stylno',ptinput);        
        query2.commandtext:='select a.custn,a.cstyl,a.mdate,a.mem,a.pprov,a.cprov,b.*,c.* from SZ_sampsize a,SZ_sampsize1 b,SZ_sampsize2 c where b.stylno=a.stylno and c.stylno=a.stylno and a.stylno=:stylno and b.kh=1';
//        query2.prepare;
        query2.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
        query2.open;
        if query2.recordcount>0 then
        begin
          ppline13.visible:=true;
          pplabel135.Visible:=true;
          ldwz1.datafield:='emeas';
          mthd4.datafield:='emethd';
          ppreport4.print;
          query3.close;
          query3.params.clear;
          query3.params.createparam(ftstring,'stylno',ptinput);          
          query3.commandtext:='select size13,size25 from SZ_sampsize2 where stylno=:stylno';
//          query3.prepare;
          query3.params[0].asstring:=frmsampletbl.table1.fieldbyname('stylno').value;
          query3.open;
          if not query3.fieldbyname('size13').isnull then
          begin
            ppline22.visible:=true;
            pplabel213.visible:=true;
            ldwz2.datafield:='emeas';
            mthd6.datafield:='emethd';
            ppreport6.print;
            if not query3.fieldbyname('size25').isnull then
            begin
             ppline30.visible:=true;
             pplabel295.visible:=true;
             ldwz3.datafield:='emeas';
             mthd8.datafield:='emethd';
             ppreport8.print;
            end;
          end;
        end;
      end;
    end;
  end;
 end;
end;

procedure Tfrmprint.ppReport1PreviewFormCreate(Sender: TObject);
begin
  ppreport1.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport1.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppReport3PreviewFormCreate(Sender: TObject);
begin
  ppreport3.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport3.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppReport2PreviewFormCreate(Sender: TObject);
begin
  ppreport2.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport2.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppReport4PreviewFormCreate(Sender: TObject);
begin
  ppreport4.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport4.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppReport5PreviewFormCreate(Sender: TObject);
begin
  ppreport5.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport5.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppReport6PreviewFormCreate(Sender: TObject);
begin
  ppreport6.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport6.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppReport7PreviewFormCreate(Sender: TObject);
begin
  ppreport7.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport7.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppReport8PreviewFormCreate(Sender: TObject);
begin
  ppreport8.PreviewForm.WindowState:=wsmaximized;
  tppviewer(ppreport8.previewform.viewer).zoompercentage:=100;
end;

procedure Tfrmprint.ppDetailBand1BeforePrint(Sender: TObject);
begin
  if length(ppdbtext13.text)>4 then ppdbtext13.font.size:=6 else ppdbtext13.font.size:=8;
  if length(ppdbtext16.text)>4 then ppdbtext16.font.size:=6 else ppdbtext16.font.size:=8;
  if length(ppdbtext19.text)>4 then ppdbtext19.font.size:=6 else ppdbtext19.font.size:=8;
  if length(ppdbtext22.text)>4 then ppdbtext22.font.size:=6 else ppdbtext22.font.size:=8;
  if length(ppdbtext47.text)>4 then ppdbtext47.font.size:=6 else ppdbtext47.font.size:=8;
  if length(ppdbtext48.text)>4 then ppdbtext48.font.size:=6 else ppdbtext48.font.size:=8;
  if length(ppdbtext49.text)>4 then ppdbtext49.font.size:=6 else ppdbtext49.font.size:=8;
  if length(ppdbtext50.text)>4 then ppdbtext50.font.size:=6 else ppdbtext50.font.size:=8;
  if length(ppdbtext51.text)>4 then ppdbtext51.font.size:=6 else ppdbtext51.font.size:=8;
  if length(ppdbtext52.text)>4 then ppdbtext52.font.size:=6 else ppdbtext52.font.size:=8;
  if length(ppdbtext53.text)>4 then ppdbtext53.font.size:=6 else ppdbtext53.font.size:=8;
  if length(ppdbtext54.text)>4 then ppdbtext54.font.size:=6 else ppdbtext54.font.size:=8;
  if length(ppdbtext55.text)>4 then ppdbtext55.font.size:=6 else ppdbtext55.font.size:=8;
  if length(ppdbtext56.text)>4 then ppdbtext56.font.size:=6 else ppdbtext56.font.size:=8;
  if length(ppdbtext57.text)>4 then ppdbtext57.font.size:=6 else ppdbtext57.font.size:=8;
  if length(ppdbtext58.text)>4 then ppdbtext58.font.size:=6 else ppdbtext58.font.size:=8;
end;

procedure Tfrmprint.ppDetailBand3BeforePrint(Sender: TObject);
begin
  if length(ppdbtext100.text)>4 then ppdbtext100.font.size:=6 else ppdbtext100.font.size:=8;
  if length(ppdbtext101.text)>4 then ppdbtext101.font.size:=6 else ppdbtext101.font.size:=8;
  if length(ppdbtext102.text)>4 then ppdbtext102.font.size:=6 else ppdbtext102.font.size:=8;
  if length(ppdbtext103.text)>4 then ppdbtext103.font.size:=6 else ppdbtext103.font.size:=8;
  if length(ppdbtext104.text)>4 then ppdbtext104.font.size:=6 else ppdbtext104.font.size:=8;
  if length(ppdbtext105.text)>4 then ppdbtext105.font.size:=6 else ppdbtext105.font.size:=8;
  if length(ppdbtext106.text)>4 then ppdbtext106.font.size:=6 else ppdbtext106.font.size:=8;
  if length(ppdbtext107.text)>4 then ppdbtext107.font.size:=6 else ppdbtext107.font.size:=8;
  if length(ppdbtext108.text)>4 then ppdbtext108.font.size:=6 else ppdbtext108.font.size:=8;
  if length(ppdbtext109.text)>4 then ppdbtext109.font.size:=6 else ppdbtext109.font.size:=8;
  if length(ppdbtext110.text)>4 then ppdbtext110.font.size:=6 else ppdbtext110.font.size:=8;
  if length(ppdbtext111.text)>4 then ppdbtext111.font.size:=6 else ppdbtext111.font.size:=8;
  if length(ppdbtext112.text)>4 then ppdbtext112.font.size:=6 else ppdbtext112.font.size:=8;
  if length(ppdbtext113.text)>4 then ppdbtext113.font.size:=6 else ppdbtext113.font.size:=8;
  if length(ppdbtext114.text)>4 then ppdbtext114.font.size:=6 else ppdbtext114.font.size:=8;
  if length(ppdbtext115.text)>4 then ppdbtext115.font.size:=6 else ppdbtext115.font.size:=8;
end;

end.
