//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8806
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.HDO.BO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.HDO;Persist Security Info=True;Use" +
            "r ID=sa")]
        public string PH_HDOConnectionString {
            get {
                return ((string)(this["PH_HDOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.HDO;User ID=sa")]
        public string PH_HDOConnectionString1 {
            get {
                return ((string)(this["PH_HDOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.HDO;User ID=sa;Password=teamwork")]
        public string PH_HDOConnectionString2 {
            get {
                return ((string)(this["PH_HDOConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240;Initial Catalog=PH.HDO;User ID=itsys")]
        public string PH_HDOConnectionString3 {
            get {
                return ((string)(this["PH_HDOConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.HDO;User ID=ituser")]
        public string PH_HDOConnectionString4 {
            get {
                return ((string)(this["PH_HDOConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PHGDB2;User ID=ituser")]
        public string PHGDB2ConnectionString {
            get {
                return ((string)(this["PHGDB2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PHGDB2;Persist Security Info=T" +
            "rue;User ID=ituser")]
        public string PHGDB2ConnectionString1 {
            get {
                return ((string)(this["PHGDB2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PH.HDO;User ID=ituser")]
        public string PH_HDOConnectionString5 {
            get {
                return ((string)(this["PH_HDOConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PH.HDO;Persist Security Info=T" +
            "rue;User ID=ituser")]
        public string PH_HDOConnectionString6 {
            get {
                return ((string)(this["PH_HDOConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PH.HDO;Persist Security Info=T" +
            "rue;User ID=ituser;Password=itsystem@2009")]
        public string PH_HDOConnectionString7 {
            get {
                return ((string)(this["PH_HDOConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.HDO;User ID=ituser;Password=itsystem@200" +
            "9")]
        public string PH_HDOConnectionString8 {
            get {
                return ((string)(this["PH_HDOConnectionString8"]));
            }
        }
    }
}
