//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8806
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.FabricInspection.BO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SqlExpress;Initial Catalog=PH.FabricInspection;Integrated Security=" +
            "True")]
        public string PH_FabricInspectionConnectionString2 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\resource\\project\\FIS2_P001145\\test\\P" +
            "HWinApp\\DataBase\\PH.FabricInspetion.mdf;Integrated Security=True;Connect Timeout" +
            "=30;User Instance=True")]
        public string PH_FabricInspetionConnectionString {
            get {
                return ((string)(this["PH_FabricInspetionConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\test;Initial Catalog=PH.FabricInspection;uid=sa;pwd=teamwo" +
            "rk")]
        public string PH_FabricInspectionConnectionString {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240\\Test;Initial Catalog=PH.FabricInspection;Persist Security " +
            "Info=True;User ID=sa;Password=teamwork")]
        public string PH_FabricInspectionConnectionString1 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240;Initial Catalog=PH.FabricInspection;User ID=itsys")]
        public string PH_FabricInspectionConnectionString3 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.240;Initial Catalog=PH.FabricInspection;User ID=itsys;Password" +
            "=uatadm1n")]
        public string PH_FabricInspectionConnectionString4 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.FabricInspection;User ID=ituser;Password" +
            "=itsystem@2009")]
        public string PH_FabricInspectionConnectionString5 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PH.FabricInspection;Persist Se" +
            "curity Info=True;User ID=ituser;Password=itsystem@2009")]
        public string PH_FabricInspectionConnectionString6 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.1.10;Initial Catalog=PH.FabricInspection;Persist Security Info=T" +
            "rue;User ID=ituser;Password=itsystem@2009")]
        public string PH_FabricInspectionConnectionString7 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S99VF403\\SQLSERVER2005;Initial Catalog=PH.FabricInspection;Persist Se" +
            "curity Info=True;User ID=ituser")]
        public string PH_FabricInspectionConnectionString8 {
            get {
                return ((string)(this["PH_FabricInspectionConnectionString8"]));
            }
        }
    }
}
